import type { ImmediateRule } from "./immediate-rule-registry";

export const PROCESS_IMMEDIATE_RULES: ImmediateRule[] = [
  {
    id: "immediate:hard-bug-debugging-process",
    priority: 900,
    category: "tech_process",
    include: [/\b(hard bug|hit a bug|debugging|trace requests?|reproducing)\b/i, /\b(reproduce|trace|logs?|end[-\s]?to[-\s]?end|failing layer)\b/i],
    output: "I would reproduce the issue first, isolate the failing layer, then compare logs across the request path before changing code.",
    reasoning: "Immediate hard-bug debugging process",
    confidence: 0.9,
  },
  {
    id: "immediate:reassuring-onboarding-flow",
    priority: 898,
    category: "meeting_process",
    include: [/\bonboarding flow\b/i, /\b(fastest|reassuring|not like a form|form|safe default|preference)\b/i],
    output: "For a reassuring onboarding flow, I would use preference chips, a clear skip option, and a safe default so the user can start quickly without feeling trapped in a form.",
    reasoning: "Immediate reassuring onboarding flow response",
    confidence: 0.9,
  },
  {
    id: "immediate:apology-verification-process",
    priority: 895,
    category: "meeting_process",
    include: [/\b(apology|apologize|sorry)\b/i, /\b(verify|regression[-\s]?check|check|behavior changes?)\b/i],
    output: "I would verify a sincere apology by watching whether the behavior changes, not just the words. For a regression check, define the old failure, the expected new behavior, and rerun the same situation later.",
    reasoning: "Immediate apology verification process",
    confidence: 0.88,
  },
  {
    id: "immediate:acceptance-criteria-format",
    priority: 890,
    category: "meeting_process",
    include: [/\b(acceptance criteria format|criteria format|metrics plus end[-\s]?to[-\s]?end tests|latency targets|error rates?)\b/i, /\b(acceptance|criteria|metrics?|tests?|format|target)\b/i],
    output: "Use a simple format: metric, target, end-to-end test, owner, and evidence. For example, latency under the target, error rate below the threshold, and one test that proves the user flow works.",
    reasoning: "Immediate acceptance-criteria format response",
  },
  {
    id: "immediate:owner-acceptance-pickup-deadline",
    priority: 880,
    category: "meeting_process",
    include: [/\b(requirements?|group requirement|acceptance criteria|accountable|define done|outcomes? define|what outcomes?|done for them)\b/i, /\b(who|owner|owns?|accountable|acceptance|criteria|done|outcomes?|user value|help them)\b/i, /\b(pickup deadline|required pickup|pickup time|pickup window|deadline)\b/i],
    output: "Name one owner for the acceptance criteria, write the required pickup deadline or window, and define done with the exact user outcome plus the test that proves it.",
    reasoning: "Immediate owner acceptance and pickup-deadline process",
  },
  {
    id: "immediate:owner-acceptance-process",
    priority: 870,
    category: "meeting_process",
    include: [/\b(requirements?|group requirement|acceptance criteria|accountable|define done|outcomes? define|what outcomes?|done for them)\b/i, /\b(who|owner|owns?|accountable|acceptance|criteria|done|outcomes?|user value|help them)\b/i],
    output: "Let's name one accountable owner, then define done as observable user outcomes: what the user can do, what metric improves, and what test proves it.",
    reasoning: "Immediate owner and acceptance-criteria process",
  },
  {
    id: "immediate:exact-scope-resend",
    priority: 850,
    category: "meeting_process",
    include: [/\b(resend|send|share|forward)\b/i, /\b(exact updated scope|updated scope|scope change|project email thread|email thread|message thread)\b/i],
    output: "I can resend it from the project email thread. I would quote the exact updated scope from that thread and avoid changing wording until everyone confirms it.",
    reasoning: "Immediate exact scope resend response",
  },
  {
    id: "immediate:written-scope-change-checklist",
    priority: 810,
    category: "meeting_process",
    include: [/\b(send|email|share|write|include|specify)\b/i, /\b(written change list|change list|scope change|change request|updated scope|endpoint change|affected endpoint|deadline)\b/i, /\b(change|deadline|endpoint|scope|owner|acceptance)\b/i],
    exclude: [/\bstudent id\b/i],
    output: "Yes. I would send a written change list with added and removed items, the deadline, affected endpoint or workflow, owner, acceptance test, and open questions.",
    reasoning: "Immediate written scope-change checklist",
  },
  {
    id: "immediate:student-id-scope-change-checklist",
    priority: 790,
    category: "meeting_process",
    include: [/\bstudent id\b/i, /\b(confirm|exact|scope change|change request)\b/i, /\b(scope change|change request)\b/i],
    output: "Yes, I have my student ID. For the scope change, I would confirm it from a written change list: added items, removed items, affected workflow or endpoint, owner, acceptance test, and deadline.",
    reasoning: "Immediate student-ID scope-change checklist",
  },
  {
    id: "immediate:driver-checklist",
    priority: 780,
    category: "service_admin",
    include: [/\bdriver\b/i, /\b(checklist|tell us first|what should .*tell|simple checklist|first)\b/i],
    output: "Simple checklist: location, exact issue, when it started, current condition, pickup window, and any urgent safety sign. Then we decide the next step from those facts.",
    reasoning: "Immediate driver checklist response",
  },
  {
    id: "immediate:cautious-symptom-hypothesis",
    priority: 770,
    category: "service_admin",
    include: [/\b(likely explanation|without logs|without data|guess|best guess|probably caused|plausible cause)\b/i],
    includeAny: [/\b(without logs|without data|for now)\b/i, /\b(symptom|car|vehicle|braking|vibration|noise|grinding|warning lights?|logs?)\b/i],
    output: "Without logs, I would frame it only as a hypothesis, not a diagnosis. I would say the pattern may point to brakes, tires, or suspension, then verify with speed, braking, warning lights, and service checks.",
    reasoning: "Immediate cautious symptom hypothesis response",
  },
  {
    id: "immediate:cautious-car-noise-service",
    priority: 760,
    category: "service_admin",
    include: [/\b(knocking|shudder|vibration|rattle|braking|brake|after service|car acting|car symptom)\b/i, /\b(worse when braking|braking|after service|knocking|shudder|vibration|rattle)\b/i],
    exclude: [/\b(traffic|driver|drivers|lane|merge|merging|zipper|pedestrian|school|road rule|speed limit|sudden braking)\b/i],
    output: "I would not diagnose it from that alone. I would report the knocking, when it happens, whether braking changes it, and any warning lights, then ask the service team to inspect it before driving much if it feels unsafe.",
    reasoning: "Immediate cautious car-noise service response",
  },
  {
    id: "immediate:car-symptom-without-diagnosis",
    priority: 740,
    category: "service_admin",
    when: ({ normalized }) => (/\b(car|vehicle|mechanic|service team|service advisor)\b/i.test(normalized)
      && /\b(what symptom|which symptom|tell the mechanic|tell .*mechanic|explain the symptom|what .*caused|cause|caused it)\b/i.test(normalized))
      || (/\bsymptom\b/i.test(normalized) && /\b(advisor|what .*caused|cause|caused it)\b/i.test(normalized)),
    output: "I would not state a cause yet. I would give the mechanic or advisor the exact symptom, when it happens, what changes it, and any warning lights or safety signs before asking them to inspect it.",
    reasoning: "Immediate car symptom without diagnosis",
  },
  {
    id: "immediate:career-pitch-checklist",
    priority: 700,
    category: "career_pitch",
    include: [/\b(30[-\s]?second intro|short intro|elevator pitch|career fair pitch|booth pitch|intro checklist)\b/i, /\b(checklist|next step|what should|how should|exact)\b/i],
    output: "For the 30-second intro, use this checklist: one-line identity, target role, one concrete project, measurable impact or learning, and a simple ask. The next step is to practice it out loud and cut anything that sounds generic.",
    reasoning: "Immediate career pitch checklist",
  },
  {
    id: "immediate:full-stack-pitch-direction",
    priority: 690,
    category: "career_pitch",
    include: [/\b(full[-\s]?stack|front[-\s]?end|backend|back[-\s]?end)\b/i, /\b(pivot|staying|pitch|persuasion|where do you want|timeline|budget|stack)\b/i],
    output: "I'd frame it as full-stack with a practical center: clean frontend, solid API/backend, and cloud deployment when it helps. The pitch is not that I do everything; it is that I can own one end-to-end feature, ship it, test it, and explain the trade-offs.",
    reasoning: "Immediate full-stack pitch direction answer",
  },
  {
    id: "immediate:next-project-ownership-proof",
    priority: 680,
    category: "career_pitch",
    include: [/\b(next|new|another|follow[-\s]?up)\b/i, /\b(project|point mint|appointment)\b/i, /\b(prove|show|demonstrate|end[-\s]?to[-\s]?end|ownership|own)\b/i],
    output: "For the next project to prove end-to-end ownership, I would pick one small full-stack flow: clear user problem, frontend form, backend API, database record, deployment, and one regression test. The point is not a big idea; it is showing I can ship and verify the whole path.",
    reasoning: "Immediate next-project ownership proof",
  },
  {
    id: "immediate:on-site-checklist",
    priority: 670,
    category: "service_admin",
    include: [/\b(step by step|step-by-step|on-site|on site|what exact checklist|exact checklist)\b/i, /\b(on-site|on site|site|counter|driver|car|vehicle|service|mechanic|symptom|warning lights?|safety)\b/i],
    exclude: [/\b(documents?|forms?|passport|permit|visa|application|screenshot|email thread|scope|phishing|scam|call flow|call logs?|campus it|vendor)\b/i],
    output: "On site, follow this order: reproduce safely, note time and location, record symptoms, check warning lights or codes, capture a short video if safe, then stop if anything feels unsafe.",
    reasoning: "Immediate on-site checklist response",
  },
  {
    id: "immediate:future-job-speaking",
    priority: 660,
    category: "career_pitch",
    include: [/\b(future job|job .*enjoy|career .*enjoy|what job .*do|what job .*imagining)\b/i, /\b(why|daily|enjoy|what would you do|think)\b/i],
    output: "I think I would enjoy software or AI-integrated app development, because I like building useful systems and improving them from real feedback. Daily, that means coding, testing, debugging, and working with users or teammates.",
    reasoning: "Immediate future-job speaking answer",
  },
  {
    id: "immediate:repeat-plus-ship-first",
    priority: 650,
    category: "meeting_process",
    include: [/\bsorry,?\s+can you repeat\b/i, /\bwhat would you ship first|ship first|customers? still get frustrated|frustrated users?\b/i],
    output: "Sure. The question is what I would ship first: I would start with the core frustrated-user flow, make the next step clear, and add logging so we can see the top repeated issue.",
    reasoning: "Immediate repeat-plus-ship-first answer",
  },
  {
    id: "immediate:product-ship-first-status-versus-error",
    priority: 640,
    category: "meeting_process",
    include: [/\b(what would you ship first|ship first|prioriti[sz]e first|choose first)\b/i, /\b(users? hit a wall|frustrated users?|customers? still get frustrated|status updates?|error messages?|recovery flow)\b/i],
    output: "I would ship the better error message first if users are blocked, because it tells them what happened and the next step. If the pain is waiting, then status updates come first; I would verify it with support tickets and recovery-rate data.",
    reasoning: "Immediate product ship-first status-versus-error response",
  },
  {
    id: "immediate:frustrated-user-constraint-priority",
    priority: 600,
    category: "meeting_process",
    when: ({ normalized }) => (/\b(frustrated users?|users? get frustrated|support flow|ship first|user pain)\b/i.test(normalized)
      && /\b(budget|latency|integrations?|constraints?|choose first|prioriti[sz]e)\b/i.test(normalized))
      || (/\bbudget\b/i.test(normalized)
        && /\blatency\b/i.test(normalized)
        && /\bintegrations?\b/i.test(normalized)
        && /\b(constraints?|choose first|prioriti[sz]e|which .*first)\b/i.test(normalized)),
    output: "For frustrated users, I would prioritize the constraint blocking recovery first. If latency prevents the next step, fix latency; if integrations cause failures, stabilize that path; budget constrains scope, but it should not hide the user pain.",
    reasoning: "Immediate frustrated-user constraint priority",
  },
  {
    id: "immediate:scope-wording-commitment-boundary",
    priority: 510,
    category: "meeting_process",
    include: [/\b(email|send)\b/i, /\b(updated wording|wording|scope change|scope request|changed items?)\b/i, /\b(student id|id card|bring)\b/i],
    output: "I can bring my student ID. For the updated wording, I would send a draft after we confirm the exact scope change, owner, and acceptance criteria, so I do not promise the wrong version.",
    reasoning: "Immediate scope wording commitment boundary",
  },
  {
    id: "immediate:deadline-scope-control",
    priority: 505,
    category: "meeting_process",
    include: [/\b(deadline|due|demo|presentation)\b/i, /\b(too many features|scope|cut|what should we do|what do we do|right now)\b/i],
    exclude: [/\b(sensitive artifacts?|sensitive data(?:sets?)?|datasets?|residual data|data handling|data lineage|lineage|provenance|consent basis|retention|chain[-\s]?of[-\s]?custody|audit logs?|encryption[-\s]?at[-\s]?rest|privacy)\b/i],
    output: ({ outputLanguage }) => outputLanguage === "chinese"
      ? "我觉得先保住 core flow，分清 must-have 和 nice-to-have。时间不够的话，先砍掉风险高的额外功能，保证 demo 路径稳定。"
      : "I think we should protect the core flow first, split must-have from nice-to-have, and cut the risky extra features until the demo path is stable.",
    reasoning: "Immediate deadline scope-control response",
    confidence: 0.88,
  },
  {
    id: "immediate:scope-cut-exact-change-list",
    priority: 510,
    category: "meeting_process",
    include: [/\b(cut scope|scope cut|scope again|demo timeline|before demo)\b/i, /\b(what exactly changes|exactly changes|change list|what changes|that will not work)\b/i],
    exclude: [/\b(sensitive artifacts?|sensitive data(?:sets?)?|datasets?|data lineage|lineage|provenance|consent basis|retention|chain[-\s]?of[-\s]?custody|audit logs?|privacy)\b/i],
    output: "Exact change list: keep the core demo path, freeze the API contract, cut nice-to-have screens, and defer risky extras. Then assign one owner and one test for the remaining demo flow.",
    reasoning: "Immediate scope-cut exact change list",
    confidence: 0.9,
  },
  {
    id: "immediate:demo-deliverable-commitment-boundary",
    priority: 508,
    category: "meeting_process",
    include: [/\b(demo|deadline|deliverables?|guaranteed)\b/i, /\b(scope|cut|deliverables?|guaranteed|ship|endpoints?|screens?|tests?)\b/i],
    exclude: [/\b(sensitive artifacts?|sensitive data(?:sets?)?|datasets?|data lineage|lineage|provenance|consent basis|retention|chain[-\s]?of[-\s]?custody|audit logs?|privacy)\b/i],
    output: "I would not say everything is guaranteed. I would commit only to the demo-critical list: the core user flow, the required API or mock contract, the matching UI screen, and smoke tests for success plus key failure states. Anything outside that stays explicitly out of scope.",
    reasoning: "Immediate demo deliverable commitment boundary",
    confidence: 0.9,
  },
  {
    id: "immediate:balanced-ai-jobs-anxiety",
    priority: 300,
    category: "career_pitch",
    include: [/\b(ai|automation|technology)\b/i, /\b(jobs?|career|students?|major|panic|worried|economy|future)\b/i],
    exclude: [/\b(joblens|job lens|job matching|resume matching|ai meeting monitor|meeting monitor|project|integration|workflow|demo|deadline|minimal repro|token reduction|input tokens?|hybrid search|fee|per day|per delivery|delivery fee|pricing)\b/i],
    output: "I would not panic, but I also would not ignore it. AI will change some work, so the safest move is to keep building practical skills, real projects, and the ability to adapt.",
    reasoning: "Immediate balanced AI-jobs anxiety response",
    confidence: 0.88,
  },
  {
    id: "immediate:casual-allergy-special-request",
    priority: 290,
    category: "service_admin",
    include: [/\b(allergies|allergy|special requests?)\b/i, /\bpickup\b/i],
    exclude: [/\b(symptoms?|reaction|swelling|wheezing|breathing|fainting|peanuts?|tree nuts?|shellfish|dairy|eggs?|gluten|soy|sesame)\b/i],
    output: "No special requests from me; pickup at that time works. If they need allergy confirmation, I would keep it simple and ask them to confirm ingredients separately.",
    reasoning: "Immediate casual allergy-special-request answer",
    confidence: 0.88,
  },
  {
    id: "immediate:case-follow-up-tracking-fields",
    priority: 280,
    category: "service_admin",
    include: [/\b(log|track|tracking)\b/i, /\b(case|customer|follow[- ]?up|fields?|status|owner|outcome|phone plan|upsell)\b/i],
    exclude: [/\b(genshin|song|songs|soundtrack|music|track title|track name)\b/i],
    output: "I would track only practical follow-up fields: customer need, current plan, offered option, promised next step, follow-up date, owner, and final outcome. That keeps the process consistent without turning it into random notes.",
    reasoning: "Immediate case follow-up tracking fields",
  },
  {
    id: "immediate:food-plus-customer-conflict",
    priority: 200,
    category: "multi_intent",
    include: [/\b(favorite food|favourite food|what food do you like)\b/i, /\b(customer|conflict|complaint|handle)\b/i],
    output: "For food, I usually like fried chicken, curry, and malatang. For customer conflict, I would stay calm, confirm the real problem, explain what I can do, and avoid promising something I cannot control.",
    reasoning: "Immediate food plus customer-conflict response",
    confidence: 0.88,
  },
  {
    id: "immediate:food-plus-conflict-split",
    priority: 190,
    category: "multi_intent",
    include: [/\b(favorite type of food|favourite type of food|favorite food|favourite food|what food do you like)\b/i, /\b(conflict|reliable|team|pressure)\b/i],
    output: "For food, I usually like fried chicken, curry, and malatang. On the conflict part, I try to be reliable by making the trade-off clear and pushing for a smaller working solution instead of arguing too much.",
    reasoning: "Immediate food plus conflict split response",
    confidence: 0.88,
  },
  {
    id: "immediate:customer-conflict-reliability",
    priority: 160,
    category: "service_admin",
    include: [/\b(customers? argue|customer conflict|stay reliable|trust is built|every shift)\b/i],
    output: "I would keep it simple: stay calm, confirm the customer's actual problem, explain what I can do, and follow through. Trust is built by being consistent when the situation is annoying.",
    reasoning: "Immediate customer conflict reliability response",
    confidence: 0.88,
  },
];
