import type { ImmediateRule } from "./immediate-rule-registry";

// Bank responsibility: classroom-style technical concepts, definitions, trade-offs, and professor/TA explanation prompts.
export const TECH_CLASSROOM_IMMEDIATE_RULES: ImmediateRule[] = [
  {
    id: "immediate:classroom-any-questions-smart-question",
    effect: "route_hint",
    route: "technical_concept",
    priority: 360,
    category: "tech_process",
    include: [/^\s*(?:any questions?|questions on (?:this|that|it|the .*?)?|does anybody have questions?|do you have any questions?)\s*[.!?]*\s*$/i],
    when: ({ signals }) => signals.previousHasClassroomTopic,
    hint: [
      "The teacher is asking for questions after a recent classroom topic. Produce one short, low-profile smart question tied to the recent topic, not a lecture answer.",
      "If the recent topic is WX plus B or linear classifiers, a good question shape is asking whether WX plus B gives class scores first and the decision comes from comparing those scores.",
    ],
    mustInclude: ["one short student-like question ending with a question mark", "connect to the recent concept or formula"],
    mustAvoid: ["personal project", "unrelated topic", "mini lecture", "I do not have the exact detail yet", "new advanced terms like logits or softmax unless already mentioned"],
    reasoning: "Immediate classroom any-questions smart-question hint",
    confidence: 0.86,
  },
  {
    id: "immediate:classroom-action-info-note",
    effect: "route_hint",
    route: "service_admin",
    priority: 360,
    category: "service_admin",
    when: ({ normalized, signals }) => signals.latestHasClassroomTaskSignal
      && (signals.previousHasClassroomTopic || /\b(class|course|professor|lecture|assignment|rubric|exam|midterm|final|homework|quiz|brightspace)\b/i.test(normalized)),
    hint: [
      "This sounds like classroom action information such as a rubric, deadline, exam hint, assignment, or requirement. Note the exact requirement and what Xiang should verify.",
      "If the latest transcript combines student ID with a rubric/form question, answer both parts separately: handle ID through the required channel, and do not invent the exact rubric or form name if it was not provided.",
    ],
    mustInclude: ["sounds like an important note or requirement", "exact item to write down or verify", "if there are two asks, address both"],
    mustAvoid: ["invented rubric details", "invented exact form name", "casually sharing student ID", "personal project unless explicitly asked", "casual small talk"],
    reasoning: "Immediate classroom action-info note hint",
    confidence: 0.86,
  },
  {
    id: "immediate:classroom-core-definition-note",
    effect: "route_hint",
    route: "technical_concept",
    priority: 260,
    category: "tech_process",
    when: ({ signals }) => signals.latestHasClassroomConceptSignal
      && signals.previousHasClassroomTopic
      && !signals.latestIsAnyQuestionsPrompt,
    hint: "The teacher just stated a core definition, formula, or concept boundary. Produce a compact note-style supplement, not a full textbook explanation.",
    mustInclude: ["compressed definition or formula", "one practical implication or example"],
    mustAvoid: ["personal project", "unrelated memory", "long explanation"],
    reasoning: "Immediate classroom core-definition note hint",
    confidence: 0.8,
  },
  {
    id: "immediate:classroom-linear-classifier-visual-template",
    effect: "route_hint",
    route: "technical_concept",
    priority: 360,
    category: "tech_process",
    when: ({ normalized }) => /\blinear classifi(?:er|cation)\b/i.test(normalized)
      && (
        /\bvisual viewpoint\b/i.test(normalized)
        || /\bimage classification\b/i.test(normalized)
        || /\bbest W and B\b/i.test(normalized)
        || (/\bW\s*(?:X|\*|x)?\s*\+?\s*B\b/i.test(normalized) && /\b(picture|image|pixel|weighted sum)\b/i.test(normalized))
      )
      && !/\b(only one template|one template image|multiple modes?|modalities|different viewpoints?)\b/i.test(normalized),
    hint: "This is a classroom linear-classifier visual-viewpoint explanation, not a personal photo or image-memory question. Let GPT write the final spoken answer naturally.",
    mustInclude: ["each row of W as one class template", "score by matching against image pixels plus bias", "limitation around multiple viewpoints or modes"],
    mustAvoid: ["photo story", "documents", "deadline", "screenshot"],
    reasoning: "Immediate classroom linear-classifier visual-template answer",
    confidence: 0.9,
  },
  {
    id: "immediate:classroom-linear-classifier-geometric-boundary",
    effect: "route_hint",
    route: "technical_concept",
    priority: 359,
    category: "tech_process",
    when: ({ normalized }) => (
      /\blinear classifi(?:er|cation)\b/i.test(normalized)
      || /\bhyperplanes?\b/i.test(normalized)
    )
      && (
        /\bhigh[-\s]?dimensional\b/i.test(normalized)
        || /\bhyperplanes?\b/i.test(normalized)
        || /\bgeometric viewpoint\b/i.test(normalized)
        || /\bnonlinear decision boundar(?:y|ies)\b/i.test(normalized)
        || /\b(draw|drawing|learns?) lines?\b/i.test(normalized)
      ),
    hint: "This is a classroom geometric-viewpoint explanation about linear classifiers. Let GPT explain the concept, not a document/deadline workflow.",
    mustInclude: ["line in 2D or hyperplane in high-dimensional space", "linearly separable data", "curved or nonlinear decision boundary limitation"],
    mustAvoid: ["documents", "deadline", "screenshot", "photo"],
    reasoning: "Immediate classroom linear-classifier geometric-boundary answer",
    confidence: 0.9,
  },
  {
    id: "immediate:classroom-linear-classifier-single-template-limit",
    effect: "route_hint",
    route: "technical_concept",
    priority: 358,
    category: "tech_process",
    include: [/\blinear classifi(?:er|cation)\b/i, /\b(template|one template|different viewpoints?|multiple modes?|modalities)\b/i],
    hint: "This is a classroom limitation explanation: linear classifiers can learn one weighted template per class and may average multiple modes.",
    mustInclude: ["one weighted template per class", "multiple viewpoints or modes", "averaging instead of separate patterns"],
    mustAvoid: ["photo story", "documents", "deadline", "screenshot"],
    reasoning: "Immediate classroom linear-classifier single-template limitation answer",
    confidence: 0.9,
  },
  {
    id: "immediate:classroom-linear-classifier-wx-plus-b",
    effect: "route_hint",
    route: "technical_concept",
    priority: 357,
    category: "tech_process",
    when: ({ normalized }) => /\blinear classifi(?:er|cation)\b/i.test(normalized)
      && (
        /\bW\s*(?:X|x)\s*\+\s*B\b/i.test(normalized)
        || /\bW into X\b/i.test(normalized)
        || /\bweighted sum\b/i.test(normalized)
      ),
    hint: "This is a classroom algebraic-viewpoint explanation of WX plus B. Let GPT produce a compact spoken explanation.",
    mustInclude: ["weighted sum of input", "bias", "score for each class", "highest score as prediction"],
    mustAvoid: ["template limitation unless asked", "documents", "deadline"],
    reasoning: "Immediate classroom linear-classifier weighted-sum answer",
    confidence: 0.9,
  },
  {
    id: "immediate:classroom-linear-regression-vs-classification",
    effect: "route_hint",
    route: "technical_concept",
    priority: 356,
    category: "tech_process",
    include: [/\blinear regression\b/i],
    exclude: [/\b(regression test|regression bug|debug regression|bisect|schema migration|config change|recent change|shows up)\b/i],
    hint: "This is a classroom distinction between linear regression and linear classification, not a software regression-debug task.",
    mustInclude: ["linear regression output is a real number", "classification uses scores", "scores become class decisions"],
    mustAvoid: ["bisect", "schema migration", "smallest repro", "debugging workflow"],
    reasoning: "Immediate classroom linear-regression versus classification answer",
    confidence: 0.9,
  },
  {
    id: "immediate:classroom-lambda-s3-dynamodb-latency",
    priority: 335,
    category: "tech_process",
    include: [/\blambda\b/i, /\blatency\b/i, /\b(s3|dynamodb)\b/i],
    output: "Lambda cold starts add latency before the code runs. S3 is usually for static assets or object storage, while DynamoDB helps when the function needs fast structured reads by key.",
    reasoning: "Immediate classroom Lambda S3 DynamoDB latency answer",
    confidence: 0.9,
  },
  {
    id: "immediate:lambda-cold-start-patient-critical",
    priority: 334,
    category: "tech_process",
    include: [/\bcold start\b/i, /\b(patient[- ]?critical|critical app|health|doctor|clinical|medical)\b/i],
    output: "Yes, cold-start delay can matter for patient-critical apps. The safe design is to keep critical paths predictable: provision or warm the function if needed, monitor latency, and avoid putting emergency decisions behind a slow serverless path.",
    reasoning: "Immediate Lambda cold-start patient-critical answer",
    confidence: 0.9,
  },
  {
    id: "immediate:patient-safety-infrastructure-tradeoff",
    priority: 333,
    category: "tech_process",
    include: [/\b(serverless|ec2|lambda)\b/i, /\b(patient safety|patient[- ]?critical|under pressure|health)\b/i],
    output: "For patient safety, I would design the critical path first, then choose infrastructure. Serverless is fine for noncritical workflows, but anything time-sensitive needs predictable latency, monitoring, fallback behavior, and a clear escalation path.",
    reasoning: "Immediate patient-safety infrastructure tradeoff",
    confidence: 0.9,
  },
  {
    id: "immediate:classroom-lambda-cold-start-definition",
    priority: 319,
    category: "tech_process",
    when: ({ normalized }) => /\blambda\b/i.test(normalized)
      && (
        /\bcold start\b/i.test(normalized)
        || (/\bstart\b/i.test(normalized) && /\b(sleep|idle|long time)\b/i.test(normalized))
        || (/\bfunction\b/i.test(normalized) && /\b(sleep|idle|long time)\b/i.test(normalized))
      ),
    output: "A Lambda cold start happens when the function has been idle and AWS has to initialize a fresh runtime before handling the request.",
    reasoning: "Immediate compact classroom lambda cold-start response",
    confidence: 0.9,
  },
  {
    id: "immediate:classroom-dynamodb-access-pattern-debug",
    priority: 318,
    category: "tech_process",
    include: [/\bdynamodb\b/i, /\b(slow|query|getting slow|access pattern|partition key|gsi|hot partition)\b/i],
    output: "Let's first check whether the query matches the partition key, sort key, or GSI. If the access pattern is wrong, capacity tuning will not really fix it.",
    reasoning: "Immediate DynamoDB meeting/debug response",
    confidence: 0.9,
  },
  {
    id: "immediate:classroom-index-read-write-tradeoff",
    priority: 317,
    category: "tech_process",
    include: [/\bindex|indexes|indices\b/i, /\bwrites?\b/i, /\breads?\b/i],
    output: "The trade-off is simple. Reads can be faster, but every write also has to maintain the index.",
    reasoning: "Immediate compact classroom index trade-off",
    confidence: 0.9,
  },
  {
    id: "immediate:classroom-database-index-lookup",
    priority: 316,
    category: "tech_process",
    include: [/\bdatabase index\b|\bindex\b.*\breads faster\b|\breads faster\b.*\bindex\b/i],
    output: "An index is like a lookup table: reads are faster because the database avoids scanning every row.",
    reasoning: "Immediate compact classroom database-index response",
    confidence: 0.9,
  },
  {
    id: "immediate:classroom-cap-theorem",
    priority: 315,
    category: "tech_process",
    include: [/\bCAP theorem\b/i],
    output: "CAP means that during a network partition, you usually have to choose consistency or availability. You cannot fully guarantee both.",
    reasoning: "Immediate compact classroom CAP response",
    confidence: 0.9,
  },
  {
    id: "immediate:classroom-tcp-three-way-handshake",
    priority: 314,
    category: "tech_process",
    include: [/\bTCP\b/i, /\bthree[-\s]?way handshake\b/i],
    output: "TCP handshake is SYN, SYN-ACK, then ACK. After that, the connection is ready to send data reliably.",
    reasoning: "Immediate compact classroom TCP handshake response",
    confidence: 0.9,
  },
  {
    id: "immediate:classroom-cloud-architecture-tradeoff",
    priority: 313,
    category: "tech_process",
    include: [/\bcloud architecture\b/i, /\bwhy|difference|traditional|trade[-\s]?off\b/i],
    output: "Cloud architecture is useful because it scales more easily, but you still have to manage cost and complexity.",
    reasoning: "Immediate compact classroom cloud-architecture response",
    confidence: 0.9,
  },
  {
    id: "immediate:classroom-serverless-cost",
    priority: 312,
    category: "tech_process",
    include: [/\bserverless\b/i, /\bcost\b/i, /\boverhead\b/i],
    output: "Serverless removes server management, but cost still depends on traffic, cold starts, and per-request pricing.",
    reasoning: "Immediate compact classroom serverless cost answer",
    confidence: 0.9,
  },
  {
    id: "immediate:classroom-password-hashing-salt",
    priority: 311,
    category: "tech_process",
    include: [/\bpasswords?\b/i, /\bhash(?:ed|ing)?\b/i, /\bsalt(?:ed|ing)?\b/i],
    output: "Hashing avoids storing raw passwords; salt makes identical passwords hash differently and blocks precomputed attacks.",
    reasoning: "Immediate compact classroom password-hashing response",
    confidence: 0.9,
  },
  {
    id: "immediate:classroom-supervised-learning-asr",
    priority: 309,
    category: "asr_correction",
    include: [/\banswer\b/i, /\bsupervis(?:e|ed)\s+learning\b/i],
    output: "Do you mean supervised learning? Basically, it learns from labeled examples.",
    reasoning: "Immediate compact classroom ASR correction for supervised learning",
    confidence: 0.9,
  },
  {
    id: "immediate:classroom-supervised-learning-limit",
    priority: 308,
    category: "tech_process",
    include: [/\b(can'?t|cannot|can't|why.*use)\b/i, /\bsupervised learning\b/i],
    output: "Because supervised learning needs labeled examples. If labels are missing or too expensive, it is not the right fit.",
    reasoning: "Immediate compact classroom supervised-learning-limit response",
    confidence: 0.9,
  },
  {
    id: "immediate:classroom-recommender-collaborative-vs-content",
    priority: 307,
    category: "tech_process",
    include: [/\bcollaborative filtering\b/i, /\bcontent[-\s]?based\b/i],
    output: "Collaborative filtering uses other users' behavior. Content-based recommendation uses item features similar to what one user already likes.",
    reasoning: "Immediate compact classroom recommender response",
    confidence: 0.9,
  },
  {
    id: "immediate:classroom-overfitting-definition",
    priority: 306,
    category: "tech_process",
    include: [/\boverfitting\b/i, /\b(machine learning|model|training|data)\b/i],
    output: "Overfitting means the model memorizes training data too much, so it performs worse on new data.",
    reasoning: "Immediate compact classroom overfitting response",
    confidence: 0.9,
  },
  {
    id: "immediate:classroom-cnn-images",
    priority: 305,
    category: "tech_process",
    include: [/\bCNNs?\b/i, /\bimages?\b/i],
    output: "CNNs work well for images because they capture local patterns like edges and shapes with shared filters.",
    reasoning: "Immediate compact classroom CNN response",
    confidence: 0.9,
  },
  {
    id: "immediate:classroom-regularization-overfit",
    priority: 304,
    category: "tech_process",
    include: [/\bregularization\b/i, /\b(model|overfit|overfitting|help)\b/i],
    output: "Regularization adds a penalty so the model does not overfit too much. Basically, it pushes the model toward a simpler solution.",
    reasoning: "Immediate compact classroom regularization response",
    confidence: 0.9,
  },
  {
    id: "immediate:classroom-learning-types",
    priority: 303,
    category: "tech_process",
    include: [/\bsemi[-\s]?supervised\b/i, /\bsupervised\b/i, /\bunsupervised\b/i, /\breinforcement\b/i],
    output: "Right, the main three are supervised, unsupervised, and reinforcement learning. Semi-supervised is more like an extra category.",
    reasoning: "Immediate compact classroom learning-types response",
    confidence: 0.9,
  },
  {
    id: "immediate:classroom-unsupervised-learning-asr",
    priority: 302,
    category: "asr_correction",
    include: [/^\s*unsurprised learning[.!?\s]*$/i],
    output: "Do you mean unsupervised learning? That means finding patterns without labels.",
    reasoning: "Immediate compact classroom ASR correction for unsupervised learning",
    confidence: 0.88,
  },
  {
    id: "immediate:classroom-computation-speed-accuracy",
    priority: 301,
    category: "tech_process",
    include: [/\bspeed and accuracy\b|\baccuracy and speed\b/i, /\bcompute|computation|computations\b/i],
    output: "The key trade-off is accuracy versus speed. First define the equation, then choose the method based on stability and cost.",
    reasoning: "Immediate compact classroom computation-tradeoff response",
    confidence: 0.88,
  },
  {
    id: "immediate:classroom-near-singular-condition",
    priority: 299,
    category: "tech_process",
    include: [/\bnearly singular\b|\bcondition number\b/i, /\bsensitive|delicate|numerically difficult|small changes\b/i],
    output: "Nearly singular means the condition number is high, so small input errors can create large output errors.",
    reasoning: "Immediate compact classroom near-singular response",
    confidence: 0.88,
  },
  {
    id: "immediate:classroom-pivoting-condition",
    priority: 298,
    category: "tech_process",
    include: [/\bpivoting\b|\bexchanging rows\b|\bwell conditioned\b|\bill conditioned\b/i],
    output: "Pivoting helps the method stay stable, but the condition number tells you how hard the problem itself is.",
    reasoning: "Immediate compact classroom pivoting-condition response",
    confidence: 0.88,
  },
  {
    id: "immediate:classroom-k-vs-a-least-squares",
    priority: 297,
    category: "tech_process",
    include: [/\bsymmetric positive\b|\btall,?\s*thin\b|\brectangular\b/i, /\bcondition number|least squares|straightforward elimination\b/i],
    output: "K is the symmetric system case; A is usually tall and rectangular, so least squares methods are the better framing.",
    reasoning: "Immediate compact classroom K-vs-A response",
    confidence: 0.88,
  },
  {
    id: "immediate:classroom-least-squares-accuracy",
    priority: 296,
    category: "tech_process",
    include: [/\bleast squares\b|\bbackslash\b|\bthousands of unknowns\b/i],
    output: "Accuracy depends on both the method and the condition number. A bad condition number can make small errors grow.",
    reasoning: "Immediate compact classroom least-squares-accuracy response",
    confidence: 0.88,
  },
  {
    id: "immediate:classroom-exam-review-scope",
    priority: 295,
    category: "tech_process",
    include: [/\bexam\b/i, /\b(condition number|gram[-\s]?schmidt|not in the exam|review)\b/i],
    output: "So basically, focus on the exam topics first, and treat condition numbers or Gram-Schmidt as extra background.",
    reasoning: "Immediate compact classroom review-scope response",
    confidence: 0.88,
  },
  {
    id: "immediate:classroom-numerical-stability-ata",
    priority: 294,
    category: "tech_process",
    includeAny: [/\bA transpose A\b/i, /\bu hat\b/i],
    output: "Using A transpose A can make the conditioning worse. So for stability, QR is usually the safer method.",
    reasoning: "Immediate compact classroom numerical-stability response",
    confidence: 0.9,
  },
  {
    id: "immediate:classroom-elastic-bar-matrix",
    priority: 293,
    category: "tech_process",
    include: [/\bA transpose C A\b/i, /\belastic bar|stretching equation|beam bending\b/i],
    output: "A transpose C A here is for the elastic bar stretching equation, not beam bending.",
    reasoning: "Immediate compact classroom elastic-bar-matrix response",
    confidence: 0.88,
  },
  {
    id: "immediate:classroom-dependent-columns",
    priority: 292,
    category: "tech_process",
    include: [/\borthonormal\b/i, /\bdependent columns?|linearly dependent|not full rank\b/i],
    output: "If A's columns are dependent, A loses rank; that is the least-squares version of a singular problem.",
    reasoning: "Immediate compact classroom dependent-columns response",
    confidence: 0.88,
  },
  {
    id: "immediate:mit-opencourseware-citation-source",
    priority: 291,
    category: "tech_process",
    include: [/\bMIT OpenCourseWare\b/i, /\bcitation format|accessed|license|terms\b/i],
    output: "This is just source and citation info. If I cite it, the main thing is to include the actual access date.",
    reasoning: "Immediate compact classroom citation-source response",
    confidence: 0.88,
  },
];
