import type { ImmediateRule } from "./immediate-rule-registry";

// Bank responsibility: general open-ended speaking topics that are broader than daily chat but not specialized risk, service, or process cases.
export const OPEN_TOPIC_IMMEDIATE_RULES: ImmediateRule[] = [
  {
      id: "immediate:soft-rain-speech-boundary",
      priority: 365,
      category: "casual",
      include: [/\bsoft rain\b/i, /\b(volume|masking speech|speech|distracts?|background)\b/i],
      output: "I would keep the soft rain low, just as background. If it starts masking speech or distracting people, lower it further or switch to silence.",
      reasoning: "Immediate soft-rain speech boundary",
      confidence: 0.88,
    },
  {
      id: "immediate:zipper-merge-traffic-flow",
      priority: 363,
      category: "casual",
      include: [/\bzipper[-\s]?merge\b/i, /\bsudden braking|braking|traffic|drivers\b/i],
      output: "Yes, zipper-merge can reduce sudden braking because drivers take turns merging instead of everyone forcing into one lane early.",
      reasoning: "Immediate zipper-merge traffic-flow answer",
      confidence: 0.88,
    },
  {
      id: "immediate:ambiguous-chops",
      priority: 360,
      category: "casual",
      include: [/\bhow are your chops\b/i],
      output: "I'm good, thanks. Nothing special, just getting through the day.",
      reasoning: "Immediate ambiguous chops response without fake hobby",
      confidence: 0.84,
    },
  {
      id: "immediate:drink-water",
      priority: 355,
      category: "casual",
      include: [/\b(i'?ll just have water|just water|water for me)\b/i],
      output: "Just water for me, thanks.",
      reasoning: "Immediate drink response without forced follow-up",
      confidence: 0.88,
    },
  {
      id: "immediate:coffee-preference",
      priority: 350,
      category: "casual",
      include: [/\bcoffee\b/i, /\b(want|drink|have|for coffee|some coffee)\b/i],
      output: "No coffee for me, thanks. Water is fine.",
      reasoning: "Immediate coffee preference response without forced follow-up",
      confidence: 0.88,
    },
  {
      id: "immediate:grounded-weekend-plan",
      effect: "route_hint",
      route: "casual",
      priority: 345,
      category: "casual",
      include: [/\bweekend\b/i, /\b(what|doing|plans?|food|games?|going out|go out)\b/i],
      hint: "This is a casual weekend-plan prompt. Keep it low-key and Xiang-like; do not invent a specific event or social plan.",
      mustInclude: ["staying in", "games or simple food", "can go out if simple"],
      mustAvoid: ["specific unsupported event", "busy social plan", "project or career context"],
      reasoning: "Immediate grounded weekend plan response",
      confidence: 0.88,
    },
  {
      id: "immediate:good-neighbor-delivery",
      priority: 340,
      category: "casual",
      include: [/\b(good neighbors?|good neighbours?|neighbours?|neighbors?)\b/i, /\b(deliver|delivery|drop[- ]?off|small help|helping|errands?|pharmacy|farm see)\b/i],
      output: "Yeah, small help like deliveries can matter, but I would keep the boundary clear. A good neighbor is considerate, communicates clearly, and helps with reasonable errands when there is a real need.",
      reasoning: "Immediate good-neighbor delivery reasoning response",
      confidence: 0.88,
    },
  {
      id: "immediate:non-speculative-stopped-playing",
      effect: "route_hint",
      route: "casual",
      priority: 335,
      category: "casual",
      include: [/\b(stopped playing|stop playing|stopped football|stopped soccer|quit playing)\b/i, /\b(ai|memory|memorization|study)\b/i],
      hint: "This is a personal hobby-causation prompt. Do not overclaim the exact reason; separate AI/memory discussion from why Xiang stopped playing football or soccer.",
      mustInclude: ["do not think AI was the reason", "not fully sure about exact cause", "schedule, environment, or priorities changing", "AI point is separate"],
      mustAvoid: ["claiming AI caused it", "invented injury", "invented team conflict"],
      reasoning: "Immediate non-speculative stopped-playing answer",
      confidence: 0.88,
    },
  {
      id: "immediate:concise-stopped-playing-reason",
      effect: "route_hint",
      route: "casual",
      priority: 330,
      category: "casual",
      include: [/\b(why did .*stop(?:ped)? playing|why .*stopped playing|why .*stop playing|why did .*quit playing|do you know why .*stopped playing)\b/i],
      exclude: [/\b(busy market|quiet shops?|legal duty|distract|responsibility)\b/i],
      hint: "This asks why Xiang stopped playing football or soccer. Answer cautiously and briefly without inventing a precise event.",
      mustInclude: ["not fully sure", "after moving to Canada", "fewer chances to play or got busier"],
      mustAvoid: ["invented injury", "invented coach or team", "overconfident exact cause"],
      reasoning: "Immediate concise stopped-playing reason",
      confidence: 0.88,
    },
  {
      id: "immediate:busy-market-asr-noise-focus",
      priority: 325,
      category: "asr_correction",
      include: [/\b(busy market|quiet shop|quiet shops|markets?)\b/i, /\b(focus|distract|legal duty|stopped playing|responsibility)\b/i],
      output: "I would treat legal duty or stopped playing as possible ASR noise there. The real point is simple: quiet shops reduce distraction, while busy markets make it harder to focus and decide calmly.",
      reasoning: "Immediate busy-market ASR-noise focus answer",
      confidence: 0.88,
    },
  {
      id: "immediate:stationery-comfort",
      effect: "route_hint",
      route: "casual",
      priority: 315,
      category: "casual",
      include: [/\b(statinary|stationary|stationery|pens?|notebooks?|tactile)\b/i, /\b(no pressure|satisfying|smell|buying|like|calm|comfort)\b/i],
      hint: "This is a casual stationery-comfort prompt. Keep it sensory and low-stakes; do not turn it into a productivity lecture.",
      mustInclude: ["small, practical, or tactile", "tiny sense of order"],
      mustAvoid: ["project context", "serious productivity system"],
      reasoning: "Immediate stationery comfort answer",
      confidence: 0.88,
    },
  {
      id: "immediate:food-plan",
      priority: 310,
      category: "casual",
      include: [/\bgrab food\b|\bget food\b|\beat later\b/i],
      output: "Sure, sounds good. Sichuan food or fried chicken both work for me.",
      reasoning: "Immediate food-plan response without forced follow-up",
      confidence: 0.86,
    },
  {
      id: "immediate:lambda-pronunciation",
      priority: 255,
      category: "asr_correction",
      include: [/\blambda\b/i, /\b(mishear|misheard|pronunciation|pronounce|lamb da|lander|learners?|wording)\b/i],
      output: "I would say it slowly as AWS Lambda, and if needed spell it out as L-a-m-b-d-a. The point is to avoid people hearing it as a normal word like lamb or lander.",
      reasoning: "Immediate Lambda pronunciation clarification",
      confidence: 0.88,
    },
  {
      id: "immediate:ai-not-a-toy-exact-wording",
      effect: "route_hint",
      route: "casual",
      priority: 235,
      category: "casual",
      include: [/\b(ai|gpt)\b/i, /\b(not[- ]?a[- ]?toy|isn.?t a toy|no longer .*toy|realization|scripted|fixed replies?|logs?|verify)\b/i, /\bexact wording|wording|records?\b/i],
      hint: "This asks for exact wording around Xiang's AI-not-a-toy realization. Keep the wording grounded and avoid claiming formal logs unless they exist.",
      mustInclude: ["AI could continue a conversation", "not fixed scripted replies", "do not claim formal logs unless verified"],
      mustAvoid: ["fake metric", "fake record", "overclaiming exact evidence"],
      reasoning: "Immediate AI-not-a-toy exact-wording answer",
    },
  {
      id: "immediate:ai-not-a-toy-realization",
      effect: "route_hint",
      route: "casual",
      priority: 230,
      category: "casual",
      include: [/\b(ai|gpt)\b/i, /\b(not[- ]?a[- ]?toy|isn.?t a toy|no longer .*toy|realization|scripted|fixed replies?|logs?|verify)\b/i],
      hint: "This is Xiang's AI-not-a-toy realization. Frame it as a practical realization, not a formal experiment unless the transcript asks for verification.",
      mustInclude: ["respond dynamically", "not fixed scripted replies", "adapt to context"],
      mustAvoid: ["fake log metric", "formal research claim"],
      reasoning: "Immediate AI-not-a-toy realization answer",
    },
  {
      id: "immediate:favorite-meal-conversation",
      priority: 220,
      category: "casual",
      include: [/\bfavorite meal\b/i, /\b(my|i'?m|i am|i like|i love|fries|pizza|burger|hungry)\b/i],
      exclude: [/\b(what'?s your|your favorite|you pick|would you pick)\b/i],
      output: "Yeah, fries make sense when you are hungry. For me, I would probably go for something simple and filling too, like curry with rice or malatang.",
      reasoning: "Immediate favorite-meal conversation response",
      confidence: 0.88,
    },
  {
      id: "immediate:simple-food-craving",
      priority: 215,
      category: "casual",
      include: [/\b(curry with rice|malatang|fries)\b/i, /\b(hungry|craving|sounds great|sounds good|eat)\b/i],
      output: "Yeah, that sounds good. I like simple filling food like that, especially when I do not want to spend too much time thinking about dinner.",
      reasoning: "Immediate simple food craving response",
      confidence: 0.86,
    },
  {
      id: "immediate:favorite-meal-grounded",
      effect: "route_hint",
      route: "casual",
      priority: 195,
      category: "casual",
      when: ({ normalized }) => /\bfavorite meal\b/i.test(normalized)
        || (/\bwhat do you pick\b/i.test(normalized) && /\bmeal|food|restaurant|manager\b/i.test(normalized)),
      hint: "This is a favorite-meal prompt. Keep it realistic and simple, not a fancy invented restaurant story.",
      mustInclude: ["simple and filling", "curry with rice or malatang"],
      mustAvoid: ["specific unsupported restaurant", "fake family meal story"],
      reasoning: "Immediate favorite meal grounded answer",
      confidence: 0.88,
    },
  {
      id: "immediate:cat-public-health-framing",
      effect: "route_hint",
      route: "casual",
      priority: 190,
      category: "casual",
      include: [/\bcat\b/i, /\bpublic health|sanitation|hygiene|germs?\b/i],
      hint: "This is a playful cat prompt with a public-health framing. Keep it light while naming hygiene, not a full policy lecture.",
      mustInclude: ["food safety, litter, or clean surfaces", "small hygiene habits affect shared spaces"],
      mustAvoid: ["heavy public-health lecture", "medical certainty"],
      reasoning: "Immediate cat public-health framing answer",
      confidence: 0.88,
    },
  {
      id: "immediate:secure-tea-asr-clarification",
      priority: 135,
      category: "asr_correction",
      include: [/\bsecure tea\b/i, /\b(timeline|overlap|notice|align|exact)\b/i],
      output: "I would clarify that term first. If 'secure tea' means quiet hours or security, we should define it, then compare the exact start and stop times before assigning the cause.",
      reasoning: "Immediate secure-tea ASR clarification",
    },
  {
      id: "immediate:rearranged-week-scheduling",
      effect: "route_hint",
      route: "casual",
      priority: 105,
      category: "casual",
      include: [/\brearrange\b/i, /\b(days of the week|week|weekend|school|events?)\b/i],
      hint: "This is an open-topic scheduling prompt. Keep it practical and simple; do not over-engineer the week.",
      mustInclude: ["keep school days and weekend days separate", "make rest more predictable"],
      mustAvoid: ["complex productivity system", "project scheduling jargon"],
      reasoning: "Immediate rearranged-week scheduling answer",
      confidence: 0.88,
    },
];
