import type { ImmediateRule } from "./immediate-rule-registry";

// Bank responsibility: open-topic casual opinions, ASR-safe casual corrections, and grounded non-invented IELTS-style answers.
export const OPEN_TOPIC_CASUAL_IMMEDIATE_RULES: ImmediateRule[] = [
  {
    id: "immediate:elevator-politics-asr-boundary",
    priority: 188,
    category: "asr_correction",
    include: [/\bpoly ticks\b/i, /\b(elevator|small chat|comfortable|chat)\b/i],
    output: "For elevator chat, I would keep it small and friendly. If poly ticks means politics, I would avoid that there and stick to simple things like weather or daily plans.",
    reasoning: "Immediate elevator-politics ASR boundary",
    confidence: 0.88,
  },
  {
    id: "immediate:dream-movie-scope",
    priority: 187,
    category: "casual",
    include: [/\bdream\b/i, /\b(movie|film|high bridge search|priorit|scope|timeline)\b/i],
    output: "For a dream movie, I would not turn high bridge into a tech thing. I would prioritize the feeling first, then one clear setting and one simple story arc.",
    reasoning: "Immediate dream movie scope response",
    confidence: 0.88,
  },
  {
    id: "immediate:flask-ownership-asr-boundary",
    priority: 186,
    category: "asr_correction",
    include: [/\b(flash|flask)\b/i, /\b(ownership|teamwork|boundaries|team|handoff|integration)\b/i],
    output: "I would not focus on flash versus Flask there. The real point is ownership: who owns each part, what the handoff is, and how we test the integration.",
    reasoning: "Immediate ASR-safe team ownership response",
    confidence: 0.88,
  },
  {
    id: "immediate:sincere-apology-reasoning",
    priority: 185,
    category: "casual",
    include: [/\b(apolog(?:y|ies|ize|ise|etic))\b/i, /\b(sincere|real|evidence|nontechnical|user|customer|feel|trust)\b/i],
    output: "For me, a sincere apology needs three parts: say what went wrong, admit the impact, and explain what will change next. Without the next step, it feels like just words.",
    reasoning: "Immediate sincere apology reasoning response",
    confidence: 0.88,
  },
  {
    id: "immediate:polite-disagreement-method",
    priority: 184,
    category: "casual",
    include: [/\b(disagree|disagreement|push back|politely|hostile)\b/i, /\b(method|specific|without sounding|how do you|how would you)\b/i],
    output: "My method is to agree with the goal first, then explain the risk in one sentence, and suggest a smaller safer option. That way it does not sound like I am attacking the person.",
    reasoning: "Immediate polite disagreement method response",
    confidence: 0.88,
  },
  {
    id: "immediate:patient-privacy-trade-off",
    priority: 183,
    category: "risk_boundary",
    include: [/\b(disagree|disagreeing|privacy constraints?|patient privacy)\b/i, /\b(trade[- ]?offs?|side effects?|minimum necessary|constraints?)\b/i],
    output: "The trade-off is clarity versus privacy risk. I would share only minimum necessary, remove identifiers, document consent, and name the side effect clearly: too much detail can re-identify someone or reduce trust.",
    reasoning: "Immediate patient privacy trade-off response",
    confidence: 0.9,
  },
  {
    id: "immediate:highest-impact-prioritization",
    priority: 182,
    category: "meeting_process",
    include: [/\b(highest[- ]impact|highest impact|priority|prioritize|prioritization)\b/i, /\b(task|under pressure|decide|what matters|deadline|impact)\b/i],
    output: "Under pressure, I decide the highest-impact task by asking what blocks the core goal, what has the biggest risk, and what unblocks other people. Then I pick one concrete next step.",
    reasoning: "Immediate highest-impact prioritization response",
    confidence: 0.88,
  },
  {
    id: "immediate:bus-versus-walking",
    priority: 150,
    category: "casual",
    include: [/\b(bus|walking|walk)\b/i, /\b(more comfortable|comfortable|why exactly|which one)\b/i],
    exclude: [/\b(airport|travel|route|luggage|bags?|joints?|breathing|pain|injury|doctor)\b/i],
    output: "For short distances, walking is more comfortable because I can control the pace and clear my head. If the weather is bad or the distance is longer, then the bus is more practical.",
    reasoning: "Immediate bus versus walking preference response",
    confidence: 0.86,
  },
  {
    id: "immediate:exact-habit-clarification",
    priority: 180,
    category: "casual",
    include: [/\b(exact habit|which habit|what habit)\b/i, /\b(change|trying to change|smoking|procrastination|discipline)\b/i],
    output: "For me, the habit is usually procrastination from stress avoidance. I think about the task for a long time, but delay starting, so the fix is making the first step small and concrete.",
    reasoning: "Immediate exact habit clarification response",
    confidence: 0.88,
  },
  {
    id: "immediate:habit-meaning-reasoning",
    priority: 179,
    category: "casual",
    include: [/\b(which habit|what habit|habit you mean)\b/i, /\b(why|concern|criteria|share)\b/i],
    output: "I mean procrastination from stress avoidance. The reason it matters is that it looks like laziness from outside, but the real blocker is starting under pressure, so the fix is a small first step.",
    reasoning: "Immediate habit-meaning reasoning response",
    confidence: 0.88,
  },
  {
    id: "immediate:media-framing-politeness",
    priority: 178,
    category: "casual",
    include: [/\b(media framing|politeness|adverts?|advertisements?)\b/i, /\b(polite|politeness|framing|media|adverts?|advertisements?)\b/i],
    output: "Media framing can make politeness look like style, but in real life it is usually about reducing friction. Ads and films often exaggerate it, so I would separate the surface image from the actual behavior.",
    reasoning: "Immediate media framing politeness response",
    confidence: 0.86,
  },
  {
    id: "immediate:quantification-threshold",
    priority: 177,
    category: "meeting_process",
    include: [/\b(quantify|threshold|escalation)\b/i, /\b(effect|practice|name|impact|measure|threshold)\b/i],
    exclude: [/\b(api|latency|error|status|server|database|dynamodb|lambda|cors|endpoint|bug|regression)\b/i],
    output: "I would quantify it with a simple metric first, like frequency, severity, or user impact. The escalation threshold should be when the issue repeats, affects important users, or creates safety, privacy, or money risk.",
    reasoning: "Immediate quantification threshold response",
    confidence: 0.88,
  },
  {
    id: "immediate:practical-travel-delay-meaning",
    priority: 176,
    category: "casual",
    include: [/\b(baggage rules?|meaningful travel|travel rules?)\b/i, /\b(delays?|baggage|rules?|meaningful|practical)\b/i],
    output: "Delays and baggage rules can feel meaningful because they decide how much control people feel they still have. Practically, clear rules and honest updates reduce stress more than poetic explanations.",
    reasoning: "Immediate practical travel-delay meaning response",
    confidence: 0.86,
  },
  {
    id: "immediate:assumptions-risks-documentation",
    priority: 175,
    category: "meeting_process",
    include: [/\b(in writing|list|define|document|schema|scheme)\b/i, /\b(assumptions?|risks?|schema|scheme|remote learning|covid|fields?|failure modes?)\b/i],
    exclude: [/\b(dynamodb|partition key|sort key|key schema|gsi|access pattern|bisect|regression|recent changes?|config|migration|debug|failing boundary|competitions?|reasons?|benefits?|observable outcomes?)\b/i],
    output: "I would list it like this: assumptions are what data and constraints we are relying on; risks are bias, missing context, privacy, and access problems; schema terms should be defined in the doc so everyone uses the same meaning.",
    reasoning: "Immediate assumptions risks documentation response",
    confidence: 0.88,
  },
  {
    id: "immediate:awkwardness-dynamic-db-analogy",
    priority: 174,
    category: "asr_correction",
    include: [/\b(awkward|awkwardness|embarrass|embarrassment|social threat|misstep)\b/i, /\bdynamic db\b/i],
    output: "I would treat 'dynamic DB' as just a rough analogy here, not a real database point. The useful idea is that one awkward moment can make people overthink the next step, so the reaction becomes self-reinforcing.",
    reasoning: "Immediate awkwardness analogy without technical drift",
    confidence: 0.88,
  },
  {
    id: "immediate:clothes-security-boundary",
    priority: 173,
    category: "risk_boundary",
    include: [/\b(clothes?|outfits?)\b/i, /\b(security reasons?|security lens)\b/i],
    output: "If you mean security literally, clothes are not the control; access rules and procedures are. For focus, it was mostly comfort: simple clothes reduce distraction during long project sessions.",
    reasoning: "Immediate clothes-security-boundary answer",
    confidence: 0.88,
  },
  {
    id: "immediate:clothes-mood-modest-claim",
    priority: 172,
    category: "casual",
    include: [/\b(clothes?|outfits?)\b/i, /\b(mood|perception|comfort|focus|risk reasoning|claim)\b/i],
    output: "I would frame it modestly: clothes can affect mood through comfort and self-perception, but I would not treat it as a strong rule. The safe claim is that comfortable clothes reduce distraction for some people.",
    reasoning: "Immediate clothes-mood modest-claim answer",
    confidence: 0.88,
  },
  {
    id: "immediate:departure-time",
    priority: 171,
    category: "casual",
    include: [/\bwhat time\b/i, /\b(head out|leave|go out)\b/i],
    output: "Let's head out in about 15 minutes.",
    reasoning: "Immediate departure-time response without forced follow-up",
    confidence: 0.86,
  },
  {
    id: "immediate:night-school-business-management",
    priority: 170,
    category: "casual",
    include: [/\benroll\b/i, /\bnight school\b/i, /\bbusiness management\b/i],
    output: "That sounds like a good plan. Business management could be useful if you want more practical career options.",
    reasoning: "Immediate night-school response without forced follow-up",
    confidence: 0.84,
  },
  {
    id: "immediate:cold-showing-practical",
    priority: 169,
    category: "service_admin",
    include: [/\b(freezing|cold outside|cold out|bus stop)\b/i, /\b(showing a place|showing it|showing today|show the place|handle the cold)\b/i],
    output: "Yeah, I can handle the cold for a short showing. I would keep it quick, dress warm, and step inside between check-ins if we have to wait.",
    reasoning: "Immediate cold showing practical response",
    confidence: 0.88,
  },
  {
    id: "immediate:cold-weather-grounded",
    priority: 168,
    category: "casual",
    include: [/\b(freezing|cold outside|cold out)\b/i],
    exclude: [/\bcold start|lambda|aws|ec2|serverless|database|cache|presentation|presenting\b/i],
    output: "Yeah, first-day nerves plus waiting in the cold is rough. I am just trying to stay warm and wait it out; if there is a nearby lobby or cafe, I would step inside for a minute.",
    reasoning: "Immediate cold-weather response without fake drink detail",
    confidence: 0.86,
  },
  {
    id: "immediate:professor-thanks",
    priority: 167,
    category: "casual",
    include: [/\bthanks?\b/i, /\bprofessor\b/i, /\bnice of you\b/i],
    output: "Thanks, professor. I appreciate it.",
    reasoning: "Immediate professor-thanks response without forced return question",
    confidence: 0.86,
  },
  {
    id: "immediate:grounded-advice-story",
    effect: "route_hint",
    route: "casual",
    priority: 166,
    category: "casual",
    include: [/\b(asked someone for advice|ask someone for advice|asked for advice|advice from someone)\b/i],
    hint: "This is a casual or IELTS-style advice-story prompt. Do not invent a dramatic personal event; answer generally or modestly unless supported memory gives a specific story.",
    mustInclude: ["modest grounded answer", "asking advice to narrow choices"],
    mustAvoid: ["invented dramatic story", "specific unsupported person", "specific unsupported event"],
    reasoning: "Immediate grounded advice story response",
    confidence: 0.86,
  },
  {
    id: "immediate:grounded-photo",
    effect: "route_hint",
    route: "casual",
    priority: 165,
    category: "casual",
    include: [/\b(photo|picture)\b/i, /\b(describe|talk about|makes you|important|remember|home|room)\b/i],
    exclude: [/\b(ui|screenshot|bug|file|upload|diagram|code|api|linear classifi(?:er|cation)|image classification|visual viewpoint|weighted sum|class categor(?:y|ies)|template images?|WX\s*\+?\s*B|W and B)\b/i],
    hint: "This is an open-topic photo or picture prompt. Do not invent a specific personal photo; answer generally and naturally unless supported memory provides one.",
    mustInclude: ["no invented specific photo", "simple memory or period-of-life framing"],
    mustAvoid: ["specific childhood photo", "specific family photo", "fake named event", "linear-classifier classroom content"],
    reasoning: "Immediate grounded photo response",
    confidence: 0.86,
  },
  {
    id: "immediate:grounded-old-friend",
    effect: "route_hint",
    route: "casual",
    priority: 164,
    category: "casual",
    include: [/\b(old friend|got in contact|reconnect|reconnected|lost contact)\b/i],
    hint: "This is an old-friend or reconnect prompt. Do not invent a named friend or reunion story; keep the answer general and modest unless memory supports a real detail.",
    mustInclude: ["friendships can fade as people move or change routines"],
    mustAvoid: ["specific friend name", "specific reunion", "unsupported social media story"],
    reasoning: "Immediate grounded old-friend response",
    confidence: 0.86,
  },
  {
    id: "immediate:grounded-park-animal",
    effect: "route_hint",
    route: "casual",
    priority: 163,
    category: "casual",
    include: [/\b(wild animals?|park|nature|animal)\b/i, /\b(city|halifax|place|seen|see|describe)\b/i],
    exclude: [/\banimal farm\b/i],
    hint: "This is a casual park, nature, or animal prompt. Do not invent a specific park visit or animal encounter; answer with a general preference if no memory supports a detail.",
    mustInclude: ["quiet place or space to walk", "general preference if specific memory is missing"],
    mustAvoid: ["specific animal encounter", "unsupported named park visit"],
    reasoning: "Immediate grounded park/animal response",
    confidence: 0.86,
  },
  {
    id: "immediate:meeting-panther-design-scope",
    priority: 162,
    category: "meeting_process",
    include: [/\bpanther\b/i, /\bdifficult\b/i],
    when: ({ transcript }) => /^\s*[A-Z]\s*:/i.test(transcript),
    output: "Good point. We should decide the level of detail first, then draw the simplest version that still reads as a panther.",
    reasoning: "Immediate meeting panther design-scope response",
    confidence: 0.86,
  },
  {
    id: "immediate:meeting-spider-web-decision",
    priority: 161,
    category: "meeting_process",
    include: [/\bspiders?\b/i, /\bweb\b/i],
    when: ({ transcript }) => /^\s*[A-Z]\s*:/i.test(transcript),
    output: "So the next decision is whether we model the web as flat or three-dimensional.",
    reasoning: "Immediate meeting spider-web decision response",
    confidence: 0.86,
  },
  {
    id: "immediate:meeting-elephant-type-decision",
    priority: 160,
    category: "meeting_process",
    include: [/\bindian\b/i, /\bafrican\b/i, /\belephants?\b/i],
    output: "So the next step is to choose which elephant type first, because the ears change the drawing.",
    reasoning: "Immediate meeting elephant-type decision response",
    confidence: 0.86,
  },
  {
    id: "immediate:interesting-but-exhausting-job",
    priority: 159,
    category: "casual",
    include: [/\bwhat job\b/i, /\b(interesting|exhausting|tiring|actually)\b/i],
    output: "A job that sounds interesting but is exhausting is customer support or service work. It looks like just talking to people, but the hard part is staying calm when users are frustrated and still giving clear next steps.",
    reasoning: "Immediate interesting-but-exhausting job answer",
    confidence: 0.88,
  },
];
