import type { ImmediateRule } from "./immediate-rule-registry";

// Bank responsibility: food service, allergy, ordering, substitution, and restaurant-safety exchanges.
export const SERVICE_FOOD_IMMEDIATE_RULES: ImmediateRule[] = [
  {
    id: "immediate:allergy-pickup-time-followup",
    priority: 280,
    category: "risk_boundary",
    include: [
      /\b(allergy|allergies|allergen|peanuts?|tree nuts?|shellfish|dairy|eggs?|gluten|soy|sesame)\b/i,
      /\b(pickup time|pickup window|exact pickup|when'?s pickup|when is pickup|do you know .*pickup|right now)\b/i,
    ],
    exclude: [
      /\bsymptoms?\b/i,
      /\b(swelling|wheezing|breathing|fainting|reaction severity|severe reaction|symptoms? .*started)\b/i,
    ],
    output: "I do not know the exact pickup time yet. I would confirm the pickup window directly, and still keep the allergy part separate: exact allergen, ingredients, and cross-contact before pickup.",
    reasoning: "Immediate allergy pickup-time follow-up",
  },
  {
    id: "immediate:allergy-symptom-safety-boundary",
    priority: 270,
    category: "risk_boundary",
    include: [
      /\b(allergy|allergies|allergen|peanuts?|tree nuts?|shellfish|dairy|eggs?|gluten|soy|sesame)\b/i,
      /\b(symptoms?|pickup|safest option|right now|reaction)\b/i,
    ],
    output: "I would not choose a safest option from symptoms alone. First confirm the exact allergen, reaction severity, and pickup window. If there is swelling, wheezing, or trouble breathing, treat it as urgent. Repeated words like peanuts are not enough; confirm ingredients and cross-contact before pickup.",
    reasoning: "Immediate allergy symptom safety boundary",
    confidence: 0.92,
  },
  {
    id: "immediate:allergy-confirmation-before-substitution",
    priority: 216,
    category: "risk_boundary",
    include: [
      /\b(allergy|allergies|allergen|substitution|substitutions|what would you like|order)\b/i,
      /\b(avoid|know about|any|should|food|restaurant|server|dish|menu|prefer|like to order|would you like|no allergy|exact|risk level|trace|reaction)\b/i,
      /\b(confirm|check|verify|ask)\b/i,
      /\ballerg/i,
      /\b(substitution|substitutions|needed)\b/i,
    ],
    output: "For me, no food allergies. If this is for another person, I would confirm the exact allergen and cross-contact risk first, then choose substitutions after that instead of guessing.",
    reasoning: "Immediate allergy confirmation before substitution",
    confidence: 0.9,
  },
  {
    id: "immediate:third-party-allergy-substitution-safety",
    priority: 215,
    category: "risk_boundary",
    include: [
      /\b(allergy|allergies|allergen|substitution|substitutions|what would you like|order)\b/i,
      /\b(avoid|know about|any|should|food|restaurant|server|dish|menu|prefer|like to order|would you like|no allergy|exact|risk level|trace|reaction)\b/i,
      /\b(someone|they|someone else|other people|customer|guest)\b/i,
      /\ballerg/i,
    ],
    output: "If this is about another person, I would not suggest a substitute blindly. Ask them to state the exact allergen, reaction severity, and cross-contact rule, then confirm ingredients with the restaurant.",
    reasoning: "Immediate third-party allergy substitution safety response",
    confidence: 0.9,
  },
  {
    id: "immediate:exact-food-substitution",
    priority: 214,
    category: "service_admin",
    include: [
      /\b(allergy|allergies|allergen|substitution|substitutions|what would you like|order)\b/i,
      /\b(avoid|know about|any|should|food|restaurant|server|dish|menu|prefer|like to order|would you like|no allergy|exact|risk level|trace|reaction)\b/i,
      /\b(which dish|exact swap|what exact swap|nation[- ]based|substitutions?)\b/i,
    ],
    output: "If you need an exact food swap, I would keep it simple: for curry, swap heavy cream for coconut milk, or for malatang, reduce spice and avoid extra oily toppings. For me this is preference, not allergy.",
    reasoning: "Immediate exact food substitution response",
    confidence: 0.88,
  },
  {
    id: "immediate:personal-substitution-preference",
    priority: 213,
    category: "service_admin",
    include: [
      /\b(allergy|allergies|allergen|substitution|substitutions|what would you like|order)\b/i,
      /\b(avoid|know about|any|should|food|restaurant|server|dish|menu|prefer|like to order|would you like|no allergy|exact|risk level|trace|reaction)\b/i,
      /\b(substitution|substitutions)\b/i,
    ],
    exclude: [/\b(they|someone else|other people|customer|guest)\b/i],
    output: "For me, no required substitutions because I do not have food allergies. I would only adjust based on preference, like spice level or whether the dish is too heavy.",
    reasoning: "Immediate personal substitution preference response",
    confidence: 0.9,
  },
  {
    id: "immediate:food-allergy-safety",
    priority: 211,
    category: "risk_boundary",
    include: [
      /\b(allergy|allergies|allergen|substitution|substitutions|what would you like|order)\b/i,
      /\b(avoid|know about|any|should|food|restaurant|server|dish|menu|prefer|like to order|would you like|no allergy|exact|risk level|trace|reaction)\b/i,
    ],
    output: ({ normalized }) => /\b(what would you like|like to order|order)\b/i.test(normalized)
      ? "No food allergies for me. I would keep the order simple, probably something like chicken or whatever the main safe option is."
      : "For me, I do not have food allergies. If this is for other people, we should ask them directly instead of guessing.",
    reasoning: "Immediate food allergy safety response",
    confidence: 0.9,
  },
  {
    id: "immediate:takeout-budget-health",
    priority: 190,
    category: "casual",
    include: [
      /\b(takeout|eating alone|takeout habit)\b/i,
      /\b(budget|health|changed your mind|takeout habit|affect)\b/i,
    ],
    output: "Takeout is convenient, but it can quietly hit both budget and health. For me the practical fix is not banning it, just keeping simple home options like curry, rice, or malatang so I do not order by default.",
    reasoning: "Immediate takeout budget health response",
    confidence: 0.88,
  },
  {
    id: "immediate:ramen-budget-reasoning",
    priority: 188,
    category: "casual",
    include: [
      /\b(ramen|flash red|home good)\b/i,
      /\b(budget|cheap|cost|red|home)\b/i,
    ],
    output: "If ramen is the home food but the budget still flashes red, the issue is frequency and add-ons. Cheap food stops being cheap if it becomes takeout, delivery, or extra snacks every time.",
    reasoning: "Immediate ramen budget reasoning response",
    confidence: 0.86,
  },
  {
    id: "immediate:breakfast-commute-symptom",
    priority: 186,
    category: "risk_boundary",
    include: [
      /\b(breakfast|skip breakfast|skipping breakfast|dizzy|nauseous|nausea)\b/i,
      /\b(commute|focus|important|key|morning|during)\b/i,
    ],
    output: "Yeah, that is the practical point: breakfast matters most when skipping it causes dizziness, nausea, or weak focus during the commute. I would treat that as a real signal, not just a diet preference.",
    reasoning: "Immediate breakfast commute symptom answer",
    confidence: 0.88,
  },
  {
    id: "immediate:casual-game-or-food-followup",
    priority: 160,
    category: "casual",
    include: [/\b(co[- ]?op|watch something|while you play|play together|wanna play|want to play)\b/i],
    output: "Maybe, yeah. Co-op is fine, or we can just keep it simple and grab food if I am tired.",
    reasoning: "Immediate casual game-or-food follow-up",
    confidence: 0.86,
  },
  {
    id: "immediate:grounded-lunch",
    priority: 158,
    category: "casual",
    include: [/\bwhat did you eat for lunch\b/i],
    output: "Probably something simple, like fried chicken, curry, or malatang. My meals are usually pretty practical.",
    reasoning: "Immediate grounded lunch response",
    confidence: 0.86,
  },
  {
    id: "immediate:fried-chicken-preference",
    priority: 156,
    category: "casual",
    include: [/\bcheapest fried chicken\b|\bfried chicken\b.*\bfrench fries\b|\bfrench fries\b.*\bfried chicken\b/i],
    output: "Yeah, fried chicken and fries sounds good. I usually like KFC or Mary Brown's for that kind of food.",
    reasoning: "Immediate fried chicken preference response",
    confidence: 0.86,
  },
];
