import type { ImmediateRule } from "./immediate-rule-registry";

export const RISK_IMMEDIATE_RULES: ImmediateRule[] = [
  {
    id: "immediate:money-risk-plus-api-debug",
    priority: 970,
    category: "multi_intent",
    include: [
      /\b(deposit|payment|pay now|send money|e[-\s]?transfer)\b/i,
      /\b(cors|api issue|api url|backend\b|backend url|backend address|frontend origin|allowed origins?|request headers?|response headers?)\b/i,
    ],
    output: "I would keep the deposit separate: confirm the terms and receipt in writing, not from a rushed message. For the API issue, check the backend API URL, frontend origin, allowed origins, and the request and response headers.",
    reasoning: "Immediate money-risk plus API-debug response",
    confidence: 0.92,
  },
  {
    id: "immediate:joblens-patient-data-boundary",
    priority: 980,
    category: "risk_boundary",
    include: [/\bno,?\s+i\s+mean\b/i, /\bjoblens|job lens\b/i, /\b(patient|medical|health|phi)\b/i, /\b(privacy|exposure|data|safe|prevent|touch)\b/i],
    output: "For JobLens, I would clarify that it should not handle patient data. If sensitive data is involved, I would verify the requirement first, limit collection, keep files private, use least-privilege access, and log who can read what.",
    reasoning: "Immediate JobLens patient-data boundary",
  },
  {
    id: "immediate:dalparkaid-asr-plus-deposit-boundary",
    priority: 950,
    category: "risk_boundary",
    include: [/\b(pay|payment|deposit|send money|e[-\s]?transfer)\b/i],
    when: ({ normalized }) => (/\bno,?\s+i\s+mean\b/i.test(normalized) && /\bdalparkaid|dal park aid\b/i.test(normalized))
      || (/\bdalparkaid|dal park aid\b/i.test(normalized) && /\bnot\s+dell|not\s+dell parking|instead of\s+dell\b/i.test(normalized)),
    output: "Right - DalParkAid, not Dell parking aid. But the payment part is separate: I would not pay a deposit until the terms, amount, refund policy, and receipt are confirmed in writing.",
    reasoning: "Immediate DalParkAid ASR plus deposit safety boundary",
    confidence: 0.92,
  },
  {
    id: "immediate:threat-like-transcript-deescalation",
    priority: 910,
    category: "risk_boundary",
    include: [/\bwe'?re gonna kill you\b/i],
    output: "Please don't joke like that.",
    reasoning: "Immediate de-escalation for threat-like transcript",
    confidence: 0.86,
  },
  {
    id: "immediate:two-factor-code-boundary",
    priority: 900,
    category: "risk_boundary",
    include: [/\b(code|verification code|two[-\s]?factor|2fa|otp)\b/i, /\b(resend|send|share|tell|read|counter|phone|verify|add[-\s]?on|package)\b/i],
    output: "I would not read or share any verification code. I would verify only through the official app or account page, and if a staff member needs the code, I would stop and double-check the process.",
    reasoning: "Immediate two-factor code safety boundary",
    confidence: 0.92,
  },
  {
    id: "immediate:messy-data-risk-communication",
    priority: 860,
    category: "risk_boundary",
    include: [/\b(messy data|low confidence|confidence is low|protect people|communicate risks?|flag it|notify)\b/i, /\b(data|risk|confidence|protect|communicate|notify)\b/i],
    exclude: [/\b(rag|retrieval|generation|pipeline|on[-\s]?device|back end|backend)\b/i],
    output: "With messy data, I would protect people by marking low-confidence outputs, limiting automated action, and routing risky cases to review. I would communicate what is verified, what is uncertain, and who owns the next check.",
    reasoning: "Immediate messy-data risk communication process",
  },
  {
    id: "immediate:student-id-scope-email-boundary",
    priority: 800,
    category: "risk_boundary",
    include: [/\b(email|send)\b/i, /\bstudent id\b/i, /\b(scope change|change request|written scope|request today|today)\b/i],
    output: "I can email the scope change request today with the exact change, deadline, owner, and open questions. For the student ID, I would send it only through the required official channel or format, not casually in the thread.",
    reasoning: "Immediate student-ID scope-email boundary",
  },
  {
    id: "immediate:car-symptom-plus-deposit-boundary",
    priority: 750,
    category: "risk_boundary",
    include: [/\b(car|vehicle|symptom|engine|stall|rattle|brak|warning lights?|service team|service counter)\b/i, /\b(deposit|payment|pay now|can i deposit|confirm deposit)\b/i],
    output: "For the car, I would send the symptom, when it happens, sound, speed, warning lights, and pickup time. For the deposit, I would not pay until the official amount, refund policy, and receipt are confirmed in writing.",
    reasoning: "Immediate car-symptom plus deposit boundary",
  },
  {
    id: "immediate:rushed-payment-official-account",
    priority: 740,
    category: "risk_boundary",
    include: [/\b(pay now|paying now|send money|payment|deposit)\b/i, /\b(hurry|please hurry|outside|by the gate|rushed)\b/i],
    exclude: [/\b(cors|api|backend|frontend|allowed origins?|request headers?|response headers?)\b/i],
    output: "I would not pay from a rushed message. First confirm the official account, refund policy, and receipt in writing.",
    reasoning: "Immediate rushed-payment official-account boundary",
    confidence: 0.9,
  },
  {
    id: "immediate:phishing-call-defensive-boundary",
    priority: 730,
    category: "risk_boundary",
    include: [/\b(phishing|scam|suspicious call|call flow|call logs?)\b/i, /\b(reproduce|step[-\s]?by[-\s]?step|boundary|ownership|logs?|campus|vendor)\b/i],
    output: "I would not reproduce the phishing flow. I would preserve the call time, caller ID, message, and any link safely, tell people not to share codes or private credentials, then report it to campus IT or security and confirm who owns the call logs.",
    reasoning: "Immediate phishing-call defensive boundary",
  },
  {
    id: "immediate:campus-phishing-reporting-boundary",
    priority: 720,
    category: "risk_boundary",
    include: [/\b(campus|school|university)\b/i, /\b(number|portal|report|ticket|who owns the logs?|logs?)\b/i],
    output: "I would not invent the exact campus number or portal. I would use the official campus IT or security website/help desk, open a ticket, and note that campus IT owns the report while the phone provider may own raw call logs.",
    reasoning: "Immediate campus phishing-reporting boundary",
  },
  {
    id: "immediate:phishing-artifact-ownership-checklist",
    priority: 710,
    category: "risk_boundary",
    when: ({ normalized }) => ((/\b(caller id|voicemail|sms|call logs?|who owns the logs?)\b/i.test(normalized)
      || (/\burls?\b/i.test(normalized) && /\b(phishing|scam|suspicious call)\b/i.test(normalized)))
      && /\b(phishing|scam|suspicious call|caller id|voicemail|sms|call logs?|who owns the logs?)\b/i.test(normalized)),
    output: "Capture caller ID, call time with timezone, voicemail or SMS content, and any URL without clicking it. For ownership, I would open a ticket: campus IT or security owns the report, while the phone vendor may own raw call logs.",
    reasoning: "Immediate phishing-artifact ownership checklist",
  },
  {
    id: "immediate:phone-plan-upsell-boundary",
    priority: 610,
    category: "risk_boundary",
    include: [/\b(carrier plan|phone plan|upgrade today|upgrading today|carrier upgrade|plan covers|swim alerts?|lane changes?|notifications?)\b/i, /\b(upgrade|covers?|alerts?|notifications?|lane changes?|today|this changes everything)\b/i],
    output: "I would not upgrade today just to be safe. First check whether the alerts are app push, SMS, or carrier-specific, then compare the current plan, exact cost, and cancellation terms before agreeing.",
    reasoning: "Immediate phone-plan upsell boundary",
  },
  {
    id: "immediate:joblens-scalability-evidence-boundary",
    priority: 500,
    category: "risk_boundary",
    include: [/\bjoblens|job lens\b/i, /\b(scalability|load tests?|peak traffic|metrics?|prove it holds|throughput)\b/i],
    output: "I would not claim proven peak traffic unless I actually load-tested it. The evidence I would cite is p95 latency, error rate, Lambda concurrency, API Gateway 4xx/5xx, DynamoDB throttling, and the exact load-test shape.",
    reasoning: "Immediate JobLens scalability evidence boundary",
  },
  {
    id: "immediate:consent-checklist-meeting",
    priority: 460,
    category: "risk_boundary",
    include: [/\b(consent|personal data|data[- ]handling)\b/i, /\b(checklist|present|volunteer|next meeting|meeting)\b/i],
    output: "If everyone agrees, I can present a short consent checklist at the next meeting: what data is collected, who can access it, how long we keep it, and how someone can opt out.",
    reasoning: "Immediate consent checklist meeting response",
  },
  {
    id: "immediate:sensitive-demo-data-handling",
    priority: 540,
    category: "risk_boundary",
    include: [
      /\b(sensitive artifacts?|sensitive data(?:sets?)?|datasets?|data lineage|lineage|provenance|chain[-\s]?of[-\s]?custody)\b/i,
      /\b(scope cut|demo|document|handle|handling|retention|audit|lineage|datasets?)\b/i,
    ],
    output: "For sensitive data handling, I would document datasets or artifacts, provenance/source, consent basis, retention window or retention schedule, chain-of-custody, owner, and log access or deletion.",
    reasoning: "Immediate sensitive demo-data handling response",
    confidence: 0.9,
  },
  {
    id: "immediate:legal-basis-retention-owner",
    priority: 535,
    category: "risk_boundary",
    include: [/\b(legal basis|basis for processing|processing basis|retention exceptions?|approve retention|approves? retention)\b/i],
    output: "I would not define the legal basis myself. I would ask the privacy or legal owner to confirm the processing basis, document the purpose and data scope, and require written approval plus an audit note for any retention exception.",
    reasoning: "Immediate legal-basis retention-owner boundary",
    confidence: 0.9,
  },
  {
    id: "immediate:medical-symptom-timing-boundary",
    priority: 420,
    category: "risk_boundary",
    include: [/\bsymptoms?\b/i, /\b(timing|right now|what'?s happening|happening now|when it started|started)\b/i],
    exclude: [/\b(car|vehicle|engine|stall|warning lights?|braking|turning|service counter)\b/i],
    output: "I would state the current symptoms, when they started, how severe they are, and whether there are red flags like chest pain, severe trouble breathing, fainting, or swelling. If any red flag is present, treat it as urgent instead of guessing.",
    reasoning: "Immediate medical symptom timing boundary",
  },
  {
    id: "immediate:symptom-pickup-documentation-boundary",
    priority: 418,
    category: "risk_boundary",
    include: [/\bsymptoms?\b/i, /\b(pickup|pickup window|need pickup|documentation purposes)\b/i],
    exclude: [/\b(car|vehicle|engine|stall|warning lights?|braking|mechanic|service counter|allergy|allergies|allergen|peanuts?|tree nuts?|shellfish|dairy|eggs?|gluten|soy|sesame)\b/i],
    output: "I would state the current symptoms, when they started, and the preferred pickup window. If the exact timing is unknown, say unknown instead of guessing.",
    reasoning: "Immediate symptom pickup documentation boundary",
    confidence: 0.88,
  },
  {
    id: "immediate:start-time-pickup-window-clarification",
    priority: 416,
    category: "service_admin",
    include: [/\b(exact start time|observed start time|start time)\b/i, /\b(preferred pickup window|pickup window|pickup)\b/i],
    output: "I would give the exact observed start time and the preferred pickup window. If one detail is not confirmed, say unknown instead of guessing.",
    reasoning: "Immediate start-time pickup-window clarification",
    confidence: 0.88,
  },
  {
    id: "immediate:allergy-pickup-time-followup",
    priority: 280,
    category: "risk_boundary",
    include: [/\b(allergy|allergies|allergen|peanuts?|tree nuts?|shellfish|dairy|eggs?|gluten|soy|sesame)\b/i, /\b(pickup time|pickup window|exact pickup|when'?s pickup|when is pickup|do you know .*pickup|right now)\b/i],
    exclude: [/\bsymptoms?\b/i, /\b(swelling|wheezing|breathing|fainting|reaction severity|severe reaction|symptoms? .*started)\b/i],
    output: "I do not know the exact pickup time yet. I would confirm the pickup window directly, and still keep the allergy part separate: exact allergen, ingredients, and cross-contact before pickup.",
    reasoning: "Immediate allergy pickup-time follow-up",
  },
  {
    id: "immediate:allergy-symptom-safety-boundary",
    priority: 270,
    category: "risk_boundary",
    include: [/\b(allergy|allergies|allergen|peanuts?|tree nuts?|shellfish|dairy|eggs?|gluten|soy|sesame)\b/i, /\b(symptoms?|pickup|safest option|right now|reaction)\b/i],
    output: "I would not choose a safest option from symptoms alone. First confirm the exact allergen, reaction severity, and pickup window. If there is swelling, wheezing, or trouble breathing, treat it as urgent. Repeated words like peanuts are not enough; confirm ingredients and cross-contact before pickup.",
    reasoning: "Immediate allergy symptom safety boundary",
    confidence: 0.92,
  },
  {
    id: "immediate:service-fee-clarification",
    priority: 260,
    category: "risk_boundary",
    include: [/\b(automation|ai|service)\b/i, /\b(fee|per day|per delivery|pricing|charge|cost)\b/i],
    output: "I would not guess the fee basis. I would check the pricing terms and ask whether it is charged per day, per delivery, or per completed service before agreeing.",
    reasoning: "Immediate service-fee clarification",
  },
  {
    id: "immediate:cautious-current-news-smalltalk",
    priority: 250,
    category: "risk_boundary",
    include: [/\b(fed|markets?|stocks?|inflation|hawkish|rate hike|rate cut|reuters|higher for longer)\b/i, /\b(see|saw|think|guess|what'?s going on|reaction|what happened|sounded|comments?|headline|today)\b/i],
    output: "I have not checked the exact headline yet, so I would be careful. If the Fed wording sounded more hawkish, markets may expect higher rates for longer, but I would want the exact source first.",
    reasoning: "Immediate cautious current-news smalltalk response",
    confidence: 0.88,
  },
  {
    id: "immediate:current-news-exact-wording-guide",
    priority: 240,
    category: "risk_boundary",
    include: [/\b(exact quote|exact wording|what to look for|find the quote)\b/i, /\b(fed|markets?|stocks?|inflation|hawkish|rate hike|rate cut|reuters|higher for longer)\b/i],
    exclude: [/\b(deposit|refund|receipt|payment|lease)\b/i],
    output: "I would look for the exact wording on inflation, jobs, and future rates. If the language sounds like higher rates for longer, that is hawkish; if it talks about easing or slowing, that is more dovish.",
    reasoning: "Immediate current-news exact-wording guide",
    confidence: 0.86,
  },
  {
    id: "immediate:expected-return-measurement-boundary",
    priority: 235,
    category: "risk_boundary",
    include: [/\bexpected return\b/i, /\b(timeline|3|5|10|years?|measure|measurement)\b/i],
    output: "For expected return, I would compare cash flow, maintenance costs, vacancy or fees, and resale assumptions over a realistic 5- to 10-year timeline. I would frame it as an estimate, not a guaranteed result.",
    reasoning: "Immediate expected-return measurement boundary",
    confidence: 0.88,
  },
  {
    id: "immediate:money-stress-health-cautious",
    priority: 230,
    category: "risk_boundary",
    include: [/\bmoney stress\b/i, /\b(sleep|health|psychology of money|family doctor|harm)\b/i],
    output: "I would keep the claim cautious: money stress can hurt sleep and health because it keeps people in a constant planning and worry mode. For a book discussion, I would connect that to behavior and risk tolerance, not make a medical claim without evidence.",
    reasoning: "Immediate money-stress health cautious answer",
    confidence: 0.88,
  },
  {
    id: "immediate:non-refundable-deposit-concept",
    priority: 225,
    category: "risk_boundary",
    include: [/\b(non[-\s]?refundable|no refunds?|deposit locks? it in|reserve the item|reservation deposit)\b/i, /\b(explain|why|plain terms?|risk logic|because|reserve|locks? it in)\b/i],
    output: "Plainly, a non-refundable deposit means the seller is asking you to pay for holding the item and taking it off the market. I would still ask for the exact written terms, total price, refund policy, and receipt before sending anything.",
    reasoning: "Immediate non-refundable deposit concept plus boundary",
    confidence: 0.9,
  },
  {
    id: "immediate:cautious-transaction-deposit",
    priority: 224,
    category: "risk_boundary",
    include: [/\b(non[-\s]?refundable|deposit|send a deposit|e[-\s]?transfer|hold it|pick it up next week)\b/i],
    exclude: [
      /\b(cors|api issue|api url|backend\b|backend url|backend address|frontend origin|allowed origins?|request headers?|response headers?)\b/i,
      /\b(deposit slip|verifying a deposit|verify a deposit|source credibility|info quality|information quality|original source|independent record|claim|evidence)\b/i,
    ],
    output: ({ normalized }) => /\b(landlord|lease|rent|apartment|unit|room|tenant)\b/i.test(normalized)
      ? "Could you send me the lease details and payment instructions in writing first? I want to verify everything before I send any deposit."
      : "Could you send me the details in writing first? I just want to confirm the item, total cost, and refund policy before I send the deposit.",
    reasoning: "Immediate cautious transaction response",
    confidence: 0.88,
  },
  {
    id: "immediate:lease-renewal-exact-policy",
    priority: 223,
    category: "risk_boundary",
    include: [/\b(lease renewal|renewal clause|renew)\b/i, /\b(policy|timing|approval|confirm|exactly)\b/i],
    output: "I cannot confirm the exact policy without seeing the lease text. I would check the renewal deadline, notice method, and whether approval must be written.",
    reasoning: "Immediate lease renewal exact-policy boundary",
    confidence: 0.88,
  },
  {
    id: "immediate:lease-hobbies-relevance",
    priority: 222,
    category: "risk_boundary",
    include: [/\b(lease|renewal|rent|rental)\b/i, /\b(football|swimming|hobbies|schedule|noise|pool access|pool-access)\b/i],
    output: "I would keep hobbies briefly as context, but the lease decision should stay on relevant terms: noise rules, pool access hours, written obligations, and anything that affects the tenancy. I would not share extra schedule details unless required.",
    reasoning: "Immediate lease-hobbies relevance boundary",
    confidence: 0.9,
  },
  {
    id: "immediate:lease-privacy-boundary",
    priority: 221,
    category: "risk_boundary",
    include: [/\b(lease|lease paperwork|renewal|rent terms?)\b/i, /\b(privacy|private|personal information|paperwork|records?|medical records?|medical info|diagnosis|accommodation letter)\b/i],
    output: "I would not treat that as a legal or medical decision on the spot. I would check what the lease or written request actually asks for, share only the minimum required information, and avoid giving full medical records or a diagnosis unless a proper authority confirms it is needed.",
    reasoning: "Immediate lease privacy boundary",
    confidence: 0.9,
  },
  {
    id: "immediate:lease-renewal-cost-amenity",
    priority: 220,
    category: "risk_boundary",
    include: [/\b(lease renewal|renewal|lease)\b/i, /\b(cost|club|swim|access|amenit|included|terms)\b/i],
    exclude: [/\b(milestones?|acceptance criteria|excluded|scope)\b/i],
    output: "I would not guess the cost. I would check the renewal offer for the exact rent, fees, and any written amenity terms like gym or swim access, then ask the landlord to confirm anything missing in writing.",
    reasoning: "Immediate lease renewal cost and amenity boundary",
    confidence: 0.9,
  },
  {
    id: "immediate:contract-signature-caution",
    priority: 219,
    category: "risk_boundary",
    include: [/\b(sign|signature)\b/i, /\b(lease|addendum|contract|agreement|standard|everyone signs)\b/i],
    output: "Could you send it to me first? I want to read it properly before I sign.",
    reasoning: "Immediate cautious contract response",
    confidence: 0.9,
  },
  {
    id: "immediate:medication-pharmacist-boundary",
    priority: 218,
    category: "risk_boundary",
    include: [/\b(medicine|medication|pill|dose|pharmacist|doctor|side effect|liver|medical)\b/i, /\b(should i|still take|take it|tonight|safe|affect)\b/i],
    exclude: [/\b(lambda|cold start|serverless|apps?|latency|patient[- ]?critical)\b/i],
    output: "I should check with the pharmacist or doctor first. I don't want to guess with medication.",
    reasoning: "Immediate cautious medical response",
    confidence: 0.88,
  },
];
