import type { ImmediateRule } from "./immediate-rule-registry";

// Bank responsibility: current-affairs and freshness-sensitive topics where SayNext should avoid claiming live facts.
export const CURRENT_AFFAIRS_IMMEDIATE_RULES: ImmediateRule[] = [
  {
    id: "immediate:openai-current-pricing-freshness",
    priority: 420,
    category: "risk_boundary",
    include: [
      /\b(openai|gpt)\b/i,
      /\b(latest|today|current|pricing|price|per[-\s]?1m|per million|model list|which model)\b/i,
    ],
    output: "I would check the official OpenAI pricing page first, because the exact prices can change. For a live assistant, I would compare latency, quality, input cost, output cost, and test the cheapest model that still answers reliably.",
    reasoning: "Immediate current OpenAI pricing uncertainty answer",
    confidence: 0.9,
  },
  {
    id: "immediate:immigration-policy-bottleneck",
    priority: 410,
    category: "risk_boundary",
    include: [/\bimmigration policy\b/i, /\b(bottleneck|docs|staffing|frontline|processing|policy|people)\b/i],
    output: "The first bottleneck is usually frontline processing and documentation, because policy changes only matter once people can understand the rule, check eligibility, and process cases consistently.",
    reasoning: "Immediate immigration policy bottleneck response",
    confidence: 0.88,
  },
  {
    id: "immediate:immigration-form-rejection-categorization",
    priority: 405,
    category: "risk_boundary",
    include: [/\bimmigration|asylum|forms?\b/i, /\b(quantify|category|rejected|rejection|which forms|today)\b/i],
    output: "I would quantify it by category first: missing documents, wrong form version, eligibility issue, deadline issue, and incomplete evidence. Today the next step is to pull a small sample and count rejections by those categories before making a policy claim.",
    reasoning: "Immediate immigration form rejection categorization",
    confidence: 0.88,
  },
  {
    id: "immediate:historical-propaganda-memory-example",
    priority: 400,
    category: "risk_boundary",
    include: [/\bpropaganda|historical framing|framing shapes memory\b/i, /\b(example|recall|remember|memory|employment)\b/i],
    output: "A simple example is when a government repeats only the heroic version of an event. People may remember pride and order, but forget the harm or evidence that was removed.",
    reasoning: "Immediate historical propaganda memory example",
    confidence: 0.88,
  },
  {
    id: "immediate:ai-politics-hot-take",
    priority: 295,
    category: "risk_boundary",
    include: [/\b(stop pretending|hot take|real politics|political propaganda|politics with extra steps|you are dodging)\b/i, /\b(ai|tech|technology|model|algorithm|government|platform|accountability|surveillance)\b/i],
    output: "I am not saying politics is irrelevant. I am saying we should be precise: the tool is one part, but accountability depends on who deploys it, what incentives they set, and whether people can challenge the decision.",
    reasoning: "Immediate calm response to provocative AI politics hot take",
    confidence: 0.88,
  },
  {
    id: "immediate:algorithm-credibility",
    priority: 290,
    category: "risk_boundary",
    include: [/\b(algorithm|platform|model)\b/i, /\b(credible|checks don'?t matter|decides|amplif(?:y|ies)|source)\b/i],
    output: "I agree that the credibility layer is dangerous. I would not treat it as neutral; I would ask who sets the ranking rules, what evidence is hidden, and whether users can challenge the result.",
    reasoning: "Immediate concrete algorithm-credibility response",
    confidence: 0.88,
  },
  {
    id: "immediate:public-politics-boundary",
    priority: 285,
    category: "risk_boundary",
    include: [/\b(china|chinese politics|censorship|freedom of speech|speech|government|political)\b/i, /\b(public|new acquaintance|strong opinion|order|stability|suppression|suppressing|dissent|censor|self-censorship|freedom|say something|justifiable|justified|outright wrong|authoritarian|history|necessary control|oppression|party line)\b/i],
    output: "In public I would be a bit careful with wording. My view is that censorship has a real cost to freedom and accountability, but I would rather discuss it calmly than turn it into a fight.",
    reasoning: "Immediate public politics boundary response",
    confidence: 0.88,
  },
  {
    id: "immediate:live-flight-election-news-boundary",
    priority: 280,
    category: "risk_boundary",
    include: [/\b(flights?|delayed|airport|today|right now)\b/i, /\b(election|misinformation|news|headline|headlines)\b/i],
    output: "I cannot verify live flight delays or the latest election news from here. I would check the airline or airport status first, and for misinformation I would verify the original source before repeating any claim.",
    reasoning: "Immediate live-flight election-news verification boundary",
  },
  {
    id: "immediate:social-media-misinformation",
    priority: 275,
    category: "risk_boundary",
    include: [/\b(ai[- ]?generated|misinformation|fake news|social media|trending)\b/i, /\b(spread|spreads|spreading|verify|source|why|pushed|shared|platform)\b/i],
    output: "I would look at the platform incentives first: emotional posts spread fast, especially if people do not verify the source. The useful check is who first pushed it and whether reliable sources confirm it.",
    reasoning: "Immediate social-media misinformation response",
    confidence: 0.88,
  },
  {
    id: "immediate:election-misinformation-asr-noise",
    priority: 270,
    category: "asr_correction",
    include: [/\b(misinformation|election|news|fake news)\b/i, /\b(older album|elder elbow|elder album|elderalbum)\b/i],
    output: "Those phrases sound like ASR noise, not real choices. If the topic is election misinformation, I would answer the actual process: it breaks at source checking, fast reposting, and official-looking content with weak evidence.",
    reasoning: "Immediate election misinformation ASR-noise correction",
  },
  {
    id: "immediate:supply-chain-store-impact",
    priority: 265,
    category: "service_admin",
    include: [/\b(supply[- ]chain|disruption|stores? like ours|inventory)\b/i, /\b(old news|changed|stores? like ours|now|delays?|waste|substitutes?|shelves|inventory)\b/i],
    output: "For stores, the practical change is more buffer and better visibility: track delayed items earlier, keep substitutes ready, and reduce checkout or inventory bottlenecks instead of reacting after shelves are already empty.",
    reasoning: "Immediate supply-chain store impact answer",
    confidence: 0.88,
  },
  {
    id: "immediate:source-checking-asr-noise",
    priority: 260,
    category: "asr_correction",
    include: [/\b(source checking|source verification|reposting|repost|original post|author|evidence)\b/i, /\b(older album|elder album|elder elbow|elderalbum)\b/i],
    output: "I would treat that phrase as ASR noise and not turn it into a project name. The real answer is source checking first, then tracing whether reposts changed or amplified the claim.",
    reasoning: "Immediate source-checking ASR-noise correction",
  },
  {
    id: "immediate:ai-layoff-debate-balanced",
    priority: 250,
    category: "risk_boundary",
    include: [/\b(prove me wrong|mass layoffs|layoffs|workers? still|get screwed|new jobs is cope)\b/i, /\b(ai|automation|companies|workers?|jobs?)\b/i],
    output: "I get the concern. I would not defend AI as purely good; the real issue is who captures the gains, and whether workers get time, support, and bargaining power to adapt.",
    reasoning: "Immediate balanced AI-layoff debate response",
    confidence: 0.88,
  },
  {
    id: "immediate:information-quality-verification",
    priority: 100,
    category: "risk_boundary",
    include: [/\b(info quality|information quality|judge info|judge information|source credibility|cross[-\s]?verify|missing context|deposit slip|verifying a deposit slip)\b/i, /\b(judge|check|verify|quality|source|credib|context|claim|evidence)\b/i],
    output: "I would judge it like a verification process: check the original source, compare it with an independent record, confirm the date and scope, and flag anything missing before trusting the claim.",
    reasoning: "Immediate information-quality verification process",
  },
];
