import type { ImmediateRule } from "./immediate-rule-registry";

export const OPEN_TOPIC_IMMEDIATE_RULES: ImmediateRule[] = [
  {
      id: "immediate:soft-rain-speech-boundary",
      priority: 365,
      category: "casual",
      include: [/\bsoft rain\b/i, /\b(volume|masking speech|speech|distracts?|background)\b/i],
      output: "I would keep the soft rain low, just as background. If it starts masking speech or distracting people, lower it further or switch to silence.",
      reasoning: "Immediate soft-rain speech boundary",
      confidence: 0.88,
    },
  {
      id: "immediate:zipper-merge-traffic-flow",
      priority: 363,
      category: "casual",
      include: [/\bzipper[-\s]?merge\b/i, /\bsudden braking|braking|traffic|drivers\b/i],
      output: "Yes, zipper-merge can reduce sudden braking because drivers take turns merging instead of everyone forcing into one lane early.",
      reasoning: "Immediate zipper-merge traffic-flow answer",
      confidence: 0.88,
    },
  {
      id: "immediate:ambiguous-chops",
      priority: 360,
      category: "casual",
      include: [/\bhow are your chops\b/i],
      output: "I'm good, thanks. Nothing special, just getting through the day.",
      reasoning: "Immediate ambiguous chops response without fake hobby",
      confidence: 0.84,
    },
  {
      id: "immediate:drink-water",
      priority: 355,
      category: "casual",
      include: [/\b(i'?ll just have water|just water|water for me)\b/i],
      output: "Just water for me, thanks.",
      reasoning: "Immediate drink response without forced follow-up",
      confidence: 0.88,
    },
  {
      id: "immediate:coffee-preference",
      priority: 350,
      category: "casual",
      include: [/\bcoffee\b/i, /\b(want|drink|have|for coffee|some coffee)\b/i],
      output: "No coffee for me, thanks. Water is fine.",
      reasoning: "Immediate coffee preference response without forced follow-up",
      confidence: 0.88,
    },
  {
      id: "immediate:grounded-weekend-plan",
      priority: 345,
      category: "casual",
      include: [/\bweekend\b/i, /\b(what|doing|plans?|food|games?|going out|go out)\b/i],
      output: "Probably just staying in most of the time, maybe games and fried chicken. I can go out if it is something simple.",
      reasoning: "Immediate grounded weekend plan response",
      confidence: 0.88,
    },
  {
      id: "immediate:good-neighbor-delivery",
      priority: 340,
      category: "casual",
      include: [/\b(good neighbors?|good neighbours?|neighbours?|neighbors?)\b/i, /\b(deliver|delivery|drop[- ]?off|small help|helping|errands?|pharmacy|farm see)\b/i],
      output: "Yeah, small help like deliveries can matter, but I would keep the boundary clear. A good neighbor is considerate, communicates clearly, and helps with reasonable errands when there is a real need.",
      reasoning: "Immediate good-neighbor delivery reasoning response",
      confidence: 0.88,
    },
  {
      id: "immediate:non-speculative-stopped-playing",
      priority: 335,
      category: "casual",
      include: [/\b(stopped playing|stop playing|stopped football|stopped soccer|quit playing)\b/i, /\b(ai|memory|memorization|study)\b/i],
      output: "I would answer carefully: I do not think AI was the reason I stopped playing. I am not fully sure about the exact cause, but it was more likely schedule, environment, or priorities changing; the AI and memory point is a separate study topic.",
      reasoning: "Immediate non-speculative stopped-playing answer",
      confidence: 0.88,
    },
  {
      id: "immediate:concise-stopped-playing-reason",
      priority: 330,
      category: "casual",
      include: [/\b(why did .*stop(?:ped)? playing|why .*stopped playing|why .*stop playing|why did .*quit playing|do you know why .*stopped playing)\b/i],
      exclude: [/\b(busy market|quiet shops?|legal duty|distract|responsibility)\b/i],
      output: "I am not fully sure, but the short version is that after moving to Canada I had fewer chances to play and got busier, so the routine faded.",
      reasoning: "Immediate concise stopped-playing reason",
      confidence: 0.88,
    },
  {
      id: "immediate:busy-market-asr-noise-focus",
      priority: 325,
      category: "asr_correction",
      include: [/\b(busy market|quiet shop|quiet shops|markets?)\b/i, /\b(focus|distract|legal duty|stopped playing|responsibility)\b/i],
      output: "I would treat legal duty or stopped playing as possible ASR noise there. The real point is simple: quiet shops reduce distraction, while busy markets make it harder to focus and decide calmly.",
      reasoning: "Immediate busy-market ASR-noise focus answer",
      confidence: 0.88,
    },
  {
      id: "immediate:stationery-comfort",
      priority: 315,
      category: "casual",
      include: [/\b(statinary|stationary|stationery|pens?|paper|notebooks?|tactile)\b/i, /\b(no pressure|satisfying|smell|buying|like|calm|comfort)\b/i],
      output: "Yeah, I get that. Stationery is satisfying because it is small, practical, and tactile; choosing a pen or paper gives a tiny sense of order without becoming a big decision.",
      reasoning: "Immediate stationery comfort answer",
      confidence: 0.88,
    },
  {
      id: "immediate:food-plan",
      priority: 310,
      category: "casual",
      include: [/\bgrab food\b|\bget food\b|\beat later\b/i],
      output: "Sure, sounds good. Sichuan food or fried chicken both work for me.",
      reasoning: "Immediate food-plan response without forced follow-up",
      confidence: 0.86,
    },
  {
      id: "immediate:lambda-pronunciation",
      priority: 255,
      category: "asr_correction",
      include: [/\blambda\b/i, /\b(mishear|misheard|pronunciation|pronounce|lamb da|lander|learners?|wording)\b/i],
      output: "I would say it slowly as AWS Lambda, and if needed spell it out as L-a-m-b-d-a. The point is to avoid people hearing it as a normal word like lamb or lander.",
      reasoning: "Immediate Lambda pronunciation clarification",
      confidence: 0.88,
    },
  {
      id: "immediate:ai-not-a-toy-exact-wording",
      priority: 235,
      category: "casual",
      include: [/\b(ai|gpt)\b/i, /\b(not[- ]?a[- ]?toy|isn.?t a toy|no longer .*toy|realization|scripted|fixed replies?|logs?|verify)\b/i, /\bexact wording|wording|records?\b/i],
      output: "The wording I would use is: AI stopped feeling like a toy when it could actually continue a conversation, not just return fixed scripted replies. I would not claim there is a formal log unless we really have one.",
      reasoning: "Immediate AI-not-a-toy exact-wording answer",
    },
  {
      id: "immediate:ai-not-a-toy-realization",
      priority: 230,
      category: "casual",
      include: [/\b(ai|gpt)\b/i, /\b(not[- ]?a[- ]?toy|isn.?t a toy|no longer .*toy|realization|scripted|fixed replies?|logs?|verify)\b/i],
      output: "The key moment was not a log metric; it was realizing the AI could respond dynamically instead of using fixed scripted replies. If I had to verify it, I would compare varied follow-up conversations and check whether it adapts to context.",
      reasoning: "Immediate AI-not-a-toy realization answer",
    },
  {
      id: "immediate:favorite-meal-conversation",
      priority: 220,
      category: "casual",
      include: [/\bfavorite meal\b/i, /\b(my|i'?m|i am|i like|i love|fries|pizza|burger|hungry)\b/i],
      exclude: [/\b(what'?s your|your favorite|you pick|would you pick)\b/i],
      output: "Yeah, fries make sense when you are hungry. For me, I would probably go for something simple and filling too, like curry with rice or malatang.",
      reasoning: "Immediate favorite-meal conversation response",
      confidence: 0.88,
    },
  {
      id: "immediate:simple-food-craving",
      priority: 215,
      category: "casual",
      include: [/\b(curry with rice|malatang|fries)\b/i, /\b(hungry|craving|sounds great|sounds good|eat)\b/i],
      output: "Yeah, that sounds good. I like simple filling food like that, especially when I do not want to spend too much time thinking about dinner.",
      reasoning: "Immediate simple food craving response",
      confidence: 0.86,
    },
  {
      id: "immediate:favorite-meal-grounded",
      priority: 195,
      category: "casual",
      when: ({ normalized }) => /\bfavorite meal\b/i.test(normalized)
        || (/\bwhat do you pick\b/i.test(normalized) && /\bmeal|food|restaurant|manager\b/i.test(normalized)),
      output: "For me, a realistic favorite meal is something simple and filling, like curry with rice or malatang. It is not fancy, but it is easy, warm, and actually something I would eat often.",
      reasoning: "Immediate favorite meal grounded answer",
      confidence: 0.88,
    },
  {
      id: "immediate:cat-public-health-framing",
      priority: 190,
      category: "casual",
      include: [/\bcat\b/i, /\bpublic health|sanitation|hygiene|germs?\b/i],
      output: "If I answer it from a public-health angle, I would keep it light: as a cat, I would notice food safety, litter, and clean surfaces. The serious point is that small hygiene habits affect shared spaces.",
      reasoning: "Immediate cat public-health framing answer",
      confidence: 0.88,
    },
  {
      id: "immediate:secure-tea-asr-clarification",
      priority: 135,
      category: "asr_correction",
      include: [/\bsecure tea\b/i, /\b(timeline|overlap|notice|align|exact)\b/i],
      output: "I would clarify that term first. If 'secure tea' means quiet hours or security, we should define it, then compare the exact start and stop times before assigning the cause.",
      reasoning: "Immediate secure-tea ASR clarification",
    },
  {
      id: "immediate:rearranged-week-scheduling",
      priority: 105,
      category: "casual",
      include: [/\brearrange\b/i, /\b(days of the week|week|weekend|school|events?)\b/i],
      output: "I would still keep school days and weekend days separate. The point of rearranging the week would be to make rest more predictable, not to blur everything together.",
      reasoning: "Immediate rearranged-week scheduling answer",
      confidence: 0.88,
    },
];
