import type { ImmediateRule } from "./immediate-rule-registry";

// Bank responsibility: open-topic questions that become risk, safety, verification, or anti-overclaiming boundaries.
export const OPEN_TOPIC_RISK_IMMEDIATE_RULES: ImmediateRule[] = [
  {
      id: "immediate:stationery-threat-model",
      priority: 320,
      category: "risk_boundary",
      include: [/\b(threat model|counterfeit|leaks?|mask risks?|risk)\b/i, /\b(statinary|stationary|stationery|pens?|paper|notebooks?|tactile)\b/i],
      output: "If we are threat-modeling it, the risk is not the stationery itself but source and trust: counterfeit materials, misleading labels, or unknown sellers. I would check seller, price, and materials before treating it as safe.",
      reasoning: "Immediate stationery threat-model answer",
      confidence: 0.88,
    },
  {
      id: "immediate:gossip-boundary-verbatim-hint",
      effect: "route_hint",
      route: "risk_boundary",
      priority: 310,
      category: "risk_boundary",
      include: [/\b(who do you tell|who should i tell|what do you say|what should i say|verbatim|in practice)\b/i],
      when: ({ normalized, previousTranscriptTexts }) => /\b(gossip|rumou?r|hearsay|team trust|protecting boundaries|reporting)\b/i.test(normalized)
        || (previousTranscriptTexts || []).some((text) => /\b(gossip|rumou?r|hearsay|team trust|protecting boundaries|reporting)\b/i.test(text)),
      hint: [
        "This is a workplace gossip/boundary wording request.",
        "Answer the latest question directly: who to tell and one short sentence Xiang can say.",
        "Do not switch to engineering requirements, prototypes, or personal-life examples.",
      ],
      mustInclude: [
        "tell an appropriate owner only if it affects work or safety",
        "one verbatim sentence",
        "avoid names and hearsay details",
      ],
      mustAvoid: ["requirements", "prototype", "normal life example", "repeat rumor details"],
      reasoning: "Immediate gossip boundary verbatim route hint",
      confidence: 0.88,
    },
  {
      id: "immediate:rumor-detail-boundary",
      priority: 305,
      category: "risk_boundary",
      include: [/\b(gossip|everyone'?s saying|vent for a sec|rumor|rumour)\b/i, /\b(exact|who said what|when|started it|name|names)\b/i],
      output: "I would not repeat exact rumor details or name people from hearsay. If the team is arguing, I would separate what we know from what people are guessing, then deal with the actual work issue.",
      reasoning: "Immediate rumor-detail boundary response",
    },
  {
      id: "immediate:coworker-gossip-boundary",
      priority: 300,
      category: "risk_boundary",
      include: [/\b(gossip|everyone'?s saying|vent for a sec|rumor|rumour)\b/i],
      output: "I can listen a little, but I don't really want to pile on or repeat rumors. If it affects work, I would keep it to what actually happened and what needs to be fixed.",
      reasoning: "Immediate coworker gossip boundary response",
      confidence: 0.88,
    },
  {
      id: "immediate:ai-not-a-toy-shipping-boundary",
      priority: 240,
      category: "risk_boundary",
      include: [/\b(ai|gpt)\b/i, /\b(not[- ]?a[- ]?toy|isn.?t a toy|no longer .*toy|realization|scripted|fixed replies?|logs?|verify)\b/i, /\b(shipping|ship|retiring|retire|today|deadline)\b/i],
      output: "I would not ship that as a big claim today. I would keep it as a personal story: AI felt different when it could continue a conversation beyond fixed replies, and only use it if we can explain it calmly.",
      reasoning: "Immediate AI-not-a-toy shipping boundary",
    },
  {
      id: "immediate:rainy-day-upsell-boundary",
      priority: 225,
      category: "risk_boundary",
      include: [/\brainy day\b/i, /\b(premium plan|upsell|subscription|offer)\b/i],
      output: "On a rainy day, I would keep it simple: stay inside, eat something warm, and do something low-pressure. I would not buy a premium plan just because someone is upselling it.",
      reasoning: "Immediate rainy-day upsell boundary",
      confidence: 0.88,
    },
  {
      id: "immediate:restaurant-roi-assumption-boundary",
      priority: 210,
      category: "risk_boundary",
      include: [/\b(restaurant|meal|delivery|residents?)\b/i, /\b(cost|roi|pay|delivery fee|price)\b/i],
      output: "I would not guess the exact cost without the menu and delivery fee. I would compare price, consistency, and repeat demand; if residents keep ordering after the real total is clear, then the ROI is more believable.",
      reasoning: "Immediate restaurant ROI assumption-boundary answer",
      confidence: 0.88,
    },
  {
      id: "immediate:bank-fraud-verification",
      priority: 185,
      category: "risk_boundary",
      include: [/\b(bank fraud|fraud call|bank call|verify a bank)\b/i, /\b(plain language|before sharing|info|information|verify|step)\b/i],
      output: "I would not share information on the call. I would hang up, use the number on the bank card or official app, and ask whether there is really a fraud alert on the account.",
      reasoning: "Immediate bank fraud verification steps",
    },
  {
      id: "immediate:phishing-risk-signal",
      priority: 180,
      category: "risk_boundary",
      include: [/\b(phishing|cybersecurity|risk signal|highest[- ]confidence)\b/i, /\b(next step|today|clean|verify|signal)\b/i],
      output: "The highest-confidence signal is a mismatch between the claimed sender and the real link or contact channel. Next step: do not click, verify through the official site or app, and report or delete the message.",
      reasoning: "Immediate phishing risk-signal answer",
    },
  {
      id: "immediate:birthday-number-boundary",
      priority: 175,
      category: "risk_boundary",
      include: [/\bbirthday\b/i, /\b(how many|guests?|budget|small treat|numbers?|exactly)\b/i],
      output: "I would not invent exact numbers. A simple version could be a few close people, a small food budget, and one small treat like cake or takeout. If this is planning a real event, I would confirm the guest count and budget first.",
      reasoning: "Immediate birthday number boundary",
      confidence: 0.88,
    },
  {
      id: "immediate:ambiguous-new-order-safety",
      priority: 160,
      category: "risk_boundary",
      include: [/\bnew order\b/i, /\bdriving|no extra details|just tell me\b/i],
      output: "I need the actual items to reorder. I should not invent a route or instruction while you are driving.",
      reasoning: "Immediate ambiguous new-order safety answer",
      confidence: 0.88,
    },
  {
      id: "immediate:patient-privacy-minimum-disclosure",
      priority: 155,
      category: "risk_boundary",
      include: [/\bpatient privacy\b/i, /\b(health|mental[- ]?health|which ones|mentioned|issues?)\b/i],
      output: "I would not name specific health or mental-health issues unless the patient already consented. The safe answer is to generalize the category, remove identifiers, and only share the minimum necessary information.",
      reasoning: "Immediate patient-privacy minimum-disclosure answer",
    },
  {
      id: "immediate:patient-privacy-protection",
      priority: 150,
      category: "risk_boundary",
      include: [/\bpatient privacy\b/i, /\b(protect|who can see|access|share|data|details|vague)\b/i],
      output: "For patient privacy, I would use the minimum-necessary rule: collect only what is needed, limit access by role, log access, and avoid sharing identifiable details unless there is a clear reason and consent.",
      reasoning: "Immediate patient privacy protection answer",
    },
  {
      id: "immediate:anonymized-versus-masked-privacy",
      priority: 145,
      category: "risk_boundary",
      include: [/\b(anonymized|anonymous|de[- ]?identified|masked)\b/i, /\b(data|patient|privacy|details|fully|just|mean)\b/i],
      output: "I would distinguish them: fully de-identified means direct identifiers are removed and re-identification risk is reduced; masked data may only hide values and can be reversible. I would still treat it as sensitive unless policy says otherwise.",
      reasoning: "Immediate anonymized-versus-masked privacy answer",
    },
  {
      id: "immediate:contract-draft-procrastination-boundary",
      priority: 140,
      category: "risk_boundary",
      include: [/\b(contract draft|contract)\b/i, /\b(procrastinat|avoidance coping|timing uncertainty|stuck|reread)\b/i],
      output: "I would frame it as stress avoidance mixed with timing uncertainty. For a contract draft, I would not give legal wording casually; I would first list the required sections, mark unclear terms, and verify anything legal before editing.",
      reasoning: "Immediate contract-draft procrastination boundary",
    },
  {
      id: "immediate:monetization-assumption-boundary",
      priority: 130,
      category: "risk_boundary",
      include: [/\b(monetization|ads|subscriptions?|premium|revenue)\b/i, /\b(assumption|assume|useful app|service[- ]?less|serverless|what)\b/i],
      output: "I would not assume monetization too early. First define the user value, then test a simple model like free basic use plus optional subscription; ads only make sense if they do not hurt trust or privacy.",
      reasoning: "Immediate monetization assumption boundary",
      confidence: 0.88,
    },
];
