import type { ImmediateRule } from "./immediate-rule-registry";

// Bank responsibility: technical implementation, debugging, architecture, API, database, and engineering-depth answers.
export const TECH_IMMEDIATE_RULES: ImmediateRule[] = [
  {
    id: "immediate:cors-allowed-origin-endpoint-check",
    priority: 840,
    category: "tech_process",
    include: [/\b(allowed origins?|allowed origin list|origin list|user storage endpoint|cors)\b/i, /\b(send|list|endpoint|origin|storage|cors)\b/i],
    exclude: [/\b(deposit|payment|refund|pay now|pay the refund|send money)\b/i],
    output: "For CORS, send the frontend origin, the backend allowed-origins list, the exact user-storage endpoint, method, status code, and request ID. I would compare Origin against the allowed list before changing config.",
    reasoning: "Immediate CORS allowed-origin endpoint check",
  },
  {
    id: "immediate:exact-endpoint-status-evidence",
    priority: 830,
    category: "tech_process",
    include: [/\b(endpoint url|exact endpoint url|http status|status code)\b/i, /\b(endpoint|url|http|status|method)\b/i],
    output: "I would not guess the endpoint. Send the exact endpoint URL, HTTP method, status code, request ID, and the response body or error text, then compare it with the API contract.",
    reasoning: "Immediate exact endpoint-status evidence request",
  },
  {
    id: "immediate:endpoint-list-writing-format",
    priority: 820,
    category: "tech_process",
    when: ({ normalized }) => (/\b(endpoint list|endpoints? list|list of endpoints|endpoint names?)\b/i.test(normalized)
      || (/\bendpoints?\b/i.test(normalized) && /\b(in writing|send|email|write|include)\b/i.test(normalized))),
    exclude: [
      /\b(403|forbidden|get vs post|post vs get|method|policy[-\s]?based|authorization|auth headers?|scopes?|endpoint url|exact endpoint|http status|status code)\b/i,
      /\b(change list|written change|scope change|change request|endpoint change|deadline)\b/i,
    ],
    output: "Yes, I have my student ID. For the endpoint list, I would send a short table: method, path, owner, auth rule, request and response schema, current status, and open questions, pulled from the API contract rather than guessed.",
    reasoning: "Immediate endpoint-list writing format",
  },
  {
    id: "immediate:generic-aws-api-logs-checklist",
    priority: 630,
    category: "tech_process",
    include: [/\b(specific logs?|aws components?|components we should check|check first|list the .*logs?)\b/i, /\b(aws|api gateway|lambda|authorizer|iam|headers?|route|method|request id)\b/i],
    output: "For an AWS API issue, I would check API Gateway access and execution logs first, then the authorizer or JWT claims, Lambda logs, and IAM or resource policy denies. I would compare the route, method, headers, and request ID against the failing response.",
    reasoning: "Immediate generic AWS API logs checklist",
  },
  {
    id: "immediate:baggage-regression-status-rule",
    priority: 620,
    category: "tech_process",
    include: [/\b(regression|test|assert|status)\b/i, /\b(missing bag|missing baggage|delayed scan|delayed status|checked)\b/i],
    output: "I would not hard-code the label. Define the status rule first: missing means no bag scan after the threshold, delayed means a scan exists but the status update is late, and checked means handoff is confirmed. Then the regression uses fixed timestamps to assert each state.",
    reasoning: "Immediate baggage regression status rule",
  },
  {
    id: "immediate:api-url-cors-evidence-request",
    priority: 590,
    category: "tech_process",
    include: [/\b(api url|backend url|frontend origin|cors|request origin)\b/i],
    exclude: [/\b(deposit|payment|refund|pay now|pay the refund|send money)\b/i],
    output: "Send the backend API URL, frontend origin, method, status code, and request and response headers. For CORS, I would compare the Origin header with the backend allowed origins before changing config.",
    reasoning: "Immediate API URL and CORS evidence request",
  },
  {
    id: "immediate:api-contract-customer-reliability",
    priority: 580,
    category: "tech_process",
    include: [/\b(api contract|lock the api contract|before integration|version endpoints?|versioning|versioned endpoints?)\b/i, /\b(customer|conflicts?|reliability|slo|slos|retries|rollback|protect)\b/i],
    output: "I would lock a v1 API contract with explicit schemas, version endpoints in the path or header, and keep backward compatibility during migration. For customers, protect retries with SLOs for error rate, latency, duplicate prevention, and rollback time.",
    reasoning: "Immediate API contract customer-reliability process",
  },
  {
    id: "immediate:schema-compatibility-ci-rollback",
    priority: 570,
    category: "tech_process",
    include: [/\b(schema compatibility|compatibility in ci|enforce schema|ci\b|rollback story|rollback under load|under load)\b/i, /\b(schema|ci|rollback|load|endpoint|contract)\b/i],
    output: "In CI, I would enforce schema compatibility with contract tests against old and new request/response fixtures. Under load, rollback should be a version switch or feature flag, with error rate and latency watched before and after the change.",
    reasoning: "Immediate schema-compatibility CI rollback process",
  },
  {
    id: "immediate:serverless-reliability-observability",
    priority: 560,
    category: "tech_process",
    when: ({ normalized }) => (/\b(serverless|lambda|function|api|service)\b/i.test(normalized)
      && /\b(quiet|reliable|reliability|attention to detail|logging|alerts?|observability|don'?t miss|miss anything)\b/i.test(normalized))
      || (/\b(logging|logs?)\b/i.test(normalized)
        && /\b(alerts?|quiet parts?|don'?t miss|miss anything|coverage)\b/i.test(normalized)),
    output: "For serverless reliability, I would use correlation IDs, structured logs, explicit error states, retries or a dead-letter queue, and alarms on failures, latency, and throttles. I would verify it by forcing a failed invocation and checking that the log and alert both appear.",
    reasoning: "Immediate serverless reliability observability mechanism",
  },
  {
    id: "immediate:serverless-tracing-debug",
    priority: 550,
    category: "tech_process",
    include: [/\b(serverless|lambda|function|api|service)\b/i, /\b(trace|tracing|logs?|request id|invocation|where do you start|breaks under uncertainty|breaks under .*traffic|debug|without ssh|ssh|observability|root cause|fails? silently)\b/i],
    output: "I would start with one invocation or request ID, check the trigger payload, error status, Lambda logs in CloudWatch, downstream retries and timeouts, then reproduce with a known-good request.",
    reasoning: "Immediate serverless tracing debug path",
  },
  {
    id: "immediate:dynamodb-partition-key-throttling",
    priority: 540,
    category: "tech_process",
    include: [/\bdynamodb\b/i, /\b(throttle|throttling|reads?|hot partition|access pattern|poor key)\b/i],
    output: "If the partition key is poor, reads can hot-spot and throttle. I would check consumed capacity by key, CloudWatch throttles, and whether the access pattern needs a better key or GSI.",
    reasoning: "Immediate DynamoDB partition-key throttling path",
  },
  {
    id: "immediate:dynamodb-partition-sort-key-design",
    priority: 530,
    category: "tech_process",
    when: ({ normalized }) => ((/\bdynamodb\b/i.test(normalized) && /\b(partition key|sort key|key schema|schema first)\b/i.test(normalized))
      || (/\bpartition key\b/i.test(normalized) && /\bsort key\b/i.test(normalized)))
      && !/\b(throttle|throttling|hot partition)\b/i.test(normalized),
    output: "I would choose the partition key from the highest-volume access pattern, not from the object shape. The sort key should support the main ordering or range query, and if another lookup is truly needed, I would add a GSI and verify consumed capacity.",
    reasoning: "Immediate DynamoDB partition-sort-key design path",
  },
  {
    id: "immediate:generic-throttling-bottleneck",
    priority: 520,
    category: "tech_process",
    include: [/\b(throttle|throttling)\b/i, /\b(queue|key|access pattern|partition|hot[- ]?spot|bottleneck|reads?|traffic|load)\b/i],
    exclude: [/\b(phone plan|carrier|unlimited|data cap|provenance|risk score|misinformation|source log)\b/i],
    output: "Yes, the queue analogy is right: if too much traffic lands on one key or partition, that spot becomes the bottleneck and requests can throttle. I would confirm it with per-key traffic, consumed capacity, CloudWatch throttles, then change the key or add a better access path.",
    reasoning: "Immediate generic throttling bottleneck path",
  },
  {
    id: "immediate:edge-case-interface-contract",
    priority: 490,
    category: "tech_process",
    include: [/\bedge cases?\b/i, /\b(defer|deferred|contract|interface|smallest safe|expose|downstream|guarantee)\b/i],
    output: "I decided by locking the smallest status contract: id, state, owner, error states or errorCode, retryable, and fallback behavior. The edge cases I logged were missing required fields, invalid state changes, failed retries, and silent-fallback attempts.",
    reasoning: "Immediate edge-case interface contract answer",
  },
  {
    id: "immediate:rag-definition-grounding",
    priority: 480,
    category: "tech_process",
    include: [/\brag\b/i, /\b(what is|what exactly|mean by|define|explain|what do you mean)\b/i],
    exclude: [/\b(pipeline|on[-\s]?device|device|back end|backend|mobile|where)\b/i],
    output: "RAG means retrieval-augmented generation: first retrieve relevant chunks from external data, put those chunks into the model context, then generate an answer grounded in that context. With messy or distributed data, I would clean, chunk, index with metadata, and show low confidence when retrieval is empty or conflicting.",
    reasoning: "Immediate RAG definition and grounding mechanism",
  },
  {
    id: "immediate:rag-incentive-side-effect",
    priority: 470,
    category: "tech_process",
    include: [/\brag\b/i, /\b(incentives?|side effects?|retriever|overfitting|gaming|measure|evaluation)\b/i],
    output: "For RAG, the mechanism is retrieval shaping generation: stale or biased retrieved chunks can make the answer look grounded but still wrong. I would measure source precision and recall, faithfulness to retrieved context, answer quality, and test on held-out queries to avoid gaming the retriever.",
    reasoning: "Immediate RAG incentive and side-effect mechanism",
  },
  {
    id: "immediate:api-403-status-unblock",
    priority: 450,
    category: "tech_process",
    include: [/\b403|forbidden|access denied|permission denied\b/i, /\b(status|highest[-\s]?risk|next step|unblock|today|right now)\b/i],
    output: "Status: root cause is not confirmed yet. Highest-risk next step is to collect one failing request ID, the response status and body, authorizer logs, token claims, and route policy, then compare them against one known-good request.",
    reasoning: "Immediate API 403 status and unblock checklist",
  },
  {
    id: "immediate:api-403-method-policy",
    priority: 440,
    category: "tech_process",
    include: [/\b(403|forbidden|access denied|permission denied)\b/i, /\b(method|get\s+vs\s+post|post\s+vs\s+get|route method|endpoint method|policy[-\s]?based)\b/i],
    output: "Yes, method can be part of the policy. I would compare the exact route and method, GET versus POST, required scopes, auth header, and request ID against the API Gateway or route-policy logs.",
    reasoning: "Immediate API 403 method-policy checklist",
  },
  {
    id: "immediate:api-403-tenant-ip-authorization",
    priority: 430,
    category: "tech_process",
    include: [/\b(403|forbidden|access denied|permission denied)\b/i, /\b(ip allowlists?|allow[-\s]?list|tenant isolation|endpoint|scope|role|claims?)\b/i],
    output: "Yes, those are authorization gates too. I would check the source IP against the allowlist, verify tenant ID and role claims, then compare the failing request and response with the route policy and request ID in logs.",
    reasoning: "Immediate API 403 tenant/IP authorization checklist",
  },
  {
    id: "immediate:end-to-end-request-tracing",
    priority: 410,
    category: "tech_process",
    include: [/\b(logs?\s+disagree|trace(?: the)? request|end[-\s]?to[-\s]?end|correlation id|request id|distributed tracing)\b/i, /\b(request|logs?|gateway|api|serverless|ec2|lambda|service|endpoint)\b/i],
    output: "I would trace one request ID end-to-end: gateway or load balancer logs, app or Lambda logs, database or downstream calls, then compare timestamps, retries, and timeouts. If the IDs are missing, reproduce with one known request and add correlation IDs first.",
    reasoning: "Immediate end-to-end request tracing debug path",
  },
  {
    id: "immediate:concrete-query-debug-logs-example",
    priority: 400,
    category: "tech_process",
    include: [/\b(exact logs?|specific example|explain output|explain analyze|output do you compare|what .*compare)\b/i, /\b(query|queries|dynamodb|postgresql|postgres|schema|logs?|explain)\b/i],
    output: "A concrete example: for PostgreSQL I would compare EXPLAIN ANALYZE scan type, index used, row estimates versus actual rows, and join order. For DynamoDB I would compare key condition, filter expression, scanned count, returned count, and consumed capacity.",
    reasoning: "Immediate concrete query debug logs example",
  },
  {
    id: "immediate:query-estimate-divergence-example",
    priority: 390,
    category: "tech_process",
    include: [/\b(specific example|estimates? diverge|root cause)\b/i, /\b(estimates? diverge|actual rows?|query plan|explain analyze|postgres|postgresql|sql|dynamodb|failing query|query)\b/i],
    output: "A concrete example: PostgreSQL estimates 100 rows but EXPLAIN ANALYZE shows 10,000 actual rows. I would check stale stats, changed filters, missing indexes, and then verify the fix with the same query on a golden dataset.",
    reasoning: "Immediate query-estimate divergence example",
  },
  {
    id: "immediate:rag-production-failure",
    priority: 380,
    category: "tech_process",
    include: [/\brag\b/i, /\b(breaks?|production|pipeline|bottlenecks?|indexing|embedding|drift|response time|latency|retrieval|generation|grounding|hallucination)\b/i],
    exclude: [/\b(on[-\s]?device|device|back end|backend|where|malformed|messy data|mobile)\b/i],
    output: "In production, RAG usually breaks in retrieval first: stale indexes, weak chunking, embedding drift, or slow retrieval. I would measure retrieval hit rate, generation latency, and whether the answer stays grounded in the retrieved context.",
    reasoning: "Immediate RAG production failure mechanism",
  },
  {
    id: "immediate:rag-device-backend-pipeline",
    priority: 370,
    category: "tech_process",
    include: [/\brag\b/i, /\b(pipeline|on[-\s]?device|device|back end|backend|missing|malformed|messy data|mobile|where)\b/i],
    output: "In a RAG pipeline, the device should validate input and show fallback states, while the backend retrieves relevant chunks in the retrieval step, adds them as context, and sends that context to the model for generation. If data is missing or malformed, mark low confidence and avoid pretending the answer is grounded.",
    reasoning: "Immediate RAG device-backend pipeline mechanism",
  },
  {
    id: "immediate:messy-data-retrieval-pipeline",
    priority: 360,
    category: "tech_process",
    include: [/\b(messy|duplicates?|nulls?|schema drift|missing fields?|conflicting chunks?|empty chunks?)\b/i, /\b(pipeline|retrieval|retrieve|index|chunk|data|rag)\b/i],
    output: "In the pipeline, messy data means duplicates, null or missing fields, schema drift, stale records, and conflicting chunks. I would dedupe, validate required fields, normalize schema, tag sources and timestamps, then retrieve only chunks that pass those checks.",
    reasoning: "Immediate messy-data retrieval pipeline definition",
  },
  {
    id: "immediate:retrieval-pipeline-bottleneck",
    priority: 350,
    category: "tech_process",
    include: [/\b(bottlenecks?|indexing latency|embedding drift|retrieval latency|response time)\b/i, /\b(indexing|embedding|retrieval|response time|latency)\b/i],
    output: "The first bottleneck is usually retrieval latency or stale indexing, then embedding drift if the data changes faster than the index updates. I would track index freshness, retrieval hit rate, p95 latency, and grounding errors separately.",
    reasoning: "Immediate retrieval pipeline bottleneck answer",
  },
  {
    id: "immediate:serverless-versus-ec2-tradeoff",
    priority: 340,
    category: "tech_process",
    include: [/\bserverless\b/i, /\bec2\b/i, /\b(trade[- ]?offs?|without hype|cost|latency|operational burden|control)\b/i],
    output: "Serverless is better for bursty workloads and lower ops work, but you accept cold starts, timeouts, and less runtime control. EC2 gives steadier control and predictable long-running compute, but you manage scaling, patching, and capacity yourself.",
    reasoning: "Immediate serverless versus EC2 trade-off",
  },
  {
    id: "immediate:cold-start-ux-mitigation",
    priority: 330,
    category: "tech_process",
    include: [/\bcold[- ]?starts?\b/i, /\b(user experience|ux|handle|mitigate|slow|timeout|latency|page load)\b/i],
    output: "For UX, I would handle cold starts by keeping the critical path warm or cached, showing a clear loading state, setting sensible timeouts, and measuring p95 latency. If it still hurts the main flow, move that path off Lambda or provision concurrency.",
    reasoning: "Immediate cold-start UX mitigation path",
  },
  {
    id: "immediate:cold-start-versus-bug-debug",
    priority: 320,
    category: "tech_process",
    include: [/\bcold[- ]?start\b/i, /\b(logs?|messy|real bugs?|bug|handler|duration|tell|distinguish|separate|debug|ec2|serverless|lambda)\b/i],
    output: "I would separate cold-start latency from a real bug by checking Lambda REPORT lines: Init Duration versus handler Duration, error stack, and request ID. If only the first invocation is slow, it is likely cold start; if warm retries still fail, debug the handler or dependency.",
    reasoning: "Immediate cold-start versus bug debug path",
  },
  {
    id: "immediate:typescript-refactor-compile-checklist",
    priority: 310,
    category: "tech_process",
    include: [/\btypescript|type script\b/i, /\b(compile error|build failing|refactor|exact error|full error|line|tsc)\b/i],
    output: "I would start with the exact TypeScript error, file, and line, then run the same build command from a clean state. After that I would check the refactored imports, exported types, tsconfig path aliases, and whether a type became too narrow.",
    reasoning: "Immediate TypeScript refactor compile checklist",
  },
  {
    id: "immediate:hybrid-search-metric-tracking",
    priority: 260,
    category: "tech_process",
    include: [/\b(input tokens?|retrieval count|answer relevance|answer faithfulness|faithfulness|metrics?|measure|track|signals?|quality stayed|stayed the same|same quality)\b/i, /\b(hybrid search|memory|retrieval|token|tokens?|chunks?|faithfulness|quality|signals?)\b/i],
    output: "I would track answer relevance, input tokens per request, retrieved chunk count, whether the right memory appears in the top results, response latency, wrong-context rate, and answer faithfulness against the retrieved evidence.",
    reasoning: "Immediate Hybrid Search metric tracking response",
  },
  {
    id: "immediate:token-reduction-minimal-repro",
    priority: 250,
    category: "tech_process",
    include: [/\b(minimal repro|repro|token reduction|input tokens?|prompt size|hybrid search memory|hybrid search)\b/i, /\b(jobless ai|job level ai|job level|jobless|token reduction|input tokens?|hybrid search)\b/i],
    output: "For a minimal repro, I would use one long transcript plus a small memory set, run it once with all memory included and once with hybrid retrieval only, then compare input tokens, retrieved chunks, and whether the final answer stays grounded.",
    reasoning: "Immediate token-reduction minimal repro response",
  },
  {
    id: "immediate:schema-evolution-query-correctness",
    priority: 240,
    category: "tech_process",
    include: [/\b(query plan|schema evolution|prove correctness|correctness)\b/i, /\b(query|schema|postgresql|postgres|dynamodb|plan|evolution)\b/i],
    output: "To prove correctness, I would use a small fixture or golden dataset and regression tests: expected rows before and after schema evolution, invariant checks for counts and required fields, and the query plan or EXPLAIN only to explain performance changes, not as the proof by itself.",
    reasoning: "Immediate schema-evolution query correctness proof",
  },
  {
    id: "immediate:changed-query-correctness-debug",
    priority: 238,
    category: "tech_process",
    include: [/\bqueries?|query\b/i, /\b(change|changed|changing|correctness|uncertainty|schema|scheme|assumptions?|dynamodb|postgresql|postgres)\b/i],
    output: "I would debug correctness with a small fixture or golden case first: capture the expected rows, run the changed query, compare filters and output counts, then check whether DynamoDB keys or GSIs, or the PostgreSQL query plan, still match the real access pattern.",
    reasoning: "Immediate changing-query correctness debug path",
  },
  {
    id: "immediate:bisect-regression-debug-process",
    priority: 236,
    category: "tech_process",
    include: [/\b(bisect|recent changes?|regression|config|schema migrations?|migration)\b/i, /\b(debug|bug|failing|failure|regression|shows up|isolate|until)\b/i],
    exclude: [/\b(baggage|missing bag|delayed scan|bag[-\s]?scan|flight time|checked,?\s+missing,?\s+or delayed|linear regression|logistic regression|regression model|regression line|statistical regression)\b/i],
    output: "Yes. I would bisect recent changes by config, schema migration, dependency, and code path, then rerun the smallest repro after each step. Once the regression appears, I would compare logs, inputs, and expected output around that exact change.",
    reasoning: "Immediate bisect-regression debug process",
  },
  {
    id: "immediate:schema-versus-scheme",
    priority: 230,
    category: "tech_process",
    include: [/\b(schema|scheme)\b/i, /\b(mean|confus|plainly|explain|plan|structure)\b/i],
    exclude: [/\b(query plan|schema evolution|prove correctness|correctness)\b/i],
    output: "Plainly, schema usually means the structure of data, like fields and types. Scheme usually means a plan or arrangement. So for a cloud or database assignment, I would say schema, not scheme.",
    reasoning: "Immediate schema versus scheme clarification",
  },
  {
    id: "immediate:git-commit-selection-release",
    priority: 300,
    category: "tech_process",
    when: ({ normalized }) => /\b(git|merge conflict|conflict|commits?|release|deadline)\b/i.test(normalized)
      && (/\b(which commits?|commits? to keep|decide .*keep|keep .*commits?|conflicting changes|right code path|which .*survive)\b/i.test(normalized)
        || (/\b(conflict hits|merge conflict)\b/i.test(normalized) && /\b(exact move|right before the deadline|before the deadline)\b/i.test(normalized)))
      && !/\b(show up|show up in git|how do .*show)\b/i.test(normalized),
    output: "I would keep only the commits needed for the release path, that still build cleanly and pass the focused tests. Risky refactors or unclear changes get deferred, and I would document which version won the conflict.",
    reasoning: "Immediate Git commit-selection release rule",
  },
];
