import type { ImmediateRule } from "./immediate-rule-registry";

// Bank responsibility: narrow debugging, regression, assertion, and failure-boundary rules that require concrete inspection paths.
export const PROCESS_DEBUG_IMMEDIATE_RULES: ImmediateRule[] = [
  {
    id: "immediate:regression-status-assertion-choice",
    priority: 626,
    category: "meeting_process",
    include: [/\b(checked|missing,?\s+or delayed)\b/i],
    output: "I would not hard-code checked, missing, or delayed until the expected behavior is defined. Assert missing if no scan appears after the threshold, delayed if the scan is late, and checked only when handoff is confirmed.",
    reasoning: "Immediate regression status assertion choice",
    confidence: 0.9,
  },
  {
    id: "immediate:baggage-regression-test-mechanism",
    priority: 612,
    category: "meeting_process",
    include: [/\b(regression test|regression|test)\b/i, /\b(baggage|delay|missing|user problem|timestamps?|scan)\b/i],
    exclude: [/\b(missing bag|missing baggage|delayed scan|delayed status|checked)\b/i],
    output: "First I would classify the user problem from evidence: missing baggage versus delayed status. The regression test should use a fixed flight time and bag-scan timeline, assert the expected status, and cover the edge case where scan data is late or missing.",
    reasoning: "Immediate baggage regression-test mechanism",
    confidence: 0.9,
  },
  {
    id: "immediate:regression-assertion-incomplete-logs",
    priority: 611,
    category: "tech_process",
    include: [/\b(regression test|regression|test)\b/i, /\b(logs? (?:are )?incomplete|incomplete logs?|without logs?|what to assert|assert without guessing|root cause)\b/i],
    output: "If logs are incomplete, I would assert the observable failure instead of guessing the root cause. First reproduce the bug, capture the input and output at the boundary, then add a test that fails before the fix and passes after it.",
    reasoning: "Immediate regression assertion under incomplete logs",
    confidence: 0.9,
  },
  {
    id: "immediate:exact-failure-debug-summary",
    priority: 610,
    category: "tech_process",
    include: [/\b(what exactly fails|exactly fails|where.*fails?|error text|error message|logs?|log lines?|current behavior|expected behavior)\b/i, /\b(fails?|error|logs?|current behavior|expected|symptoms?|where|writing|debug)\b/i],
    exclude: [/\b(lambda|cold[- ]?start|serverless|api gateway|dynamodb|cors|403|forbidden|query plan|query debug|query correctness|explain|explain analyze|specific example|output .*compare|customer|case|follow[- ]?up|tracking fields?|track .*fields?|edge cases?|interface contract|smallest safe|smallest status contract|logs?\s+disagree|trace(?: the)? request|end[-\s]?to[-\s]?end|correlation id|definition of done|done means|merged .*pr|integration sprint|demo meeting log|refund|chargebacks?|fraud|data exposure|lock down|front desk|elder elbow|older album|mentor support|talk to him|log it)\b/i],
    output: "In writing, I would capture the exact failing step, where it fails, expected versus actual behavior, the full error text, relevant log lines, timestamp or request ID, and the last change before the failure. If any field is unknown, mark it unknown.",
    reasoning: "Immediate exact failure debug summary",
    confidence: 0.9,
  },
  {
    id: "immediate:response-window-escalation-process",
    priority: 609,
    category: "meeting_process",
    include: [/\b(response windows?|late see|latency|escalation path|pressure spikes?)\b/i, /\b(define|writing|escalation|pressure|window|response)\b/i],
    exclude: [/\b(indexing|embedding|retrieval|bottlenecks?|response time|p95|pipeline|rag|cold start|serverless|lambda)\b/i],
    output: "I would define it simply: normal response within one business day, urgent issues use the escalation channel, and if pressure spikes we pause new requests and agree on the top priority in writing.",
    reasoning: "Immediate response-window escalation process response",
    confidence: 0.88,
  },
  {
    id: "immediate:process-safe-room-status-update",
    priority: 608,
    category: "service_admin",
    include: [/\b(room problem|room issue|maintenance|repair|status update|updates?)\b/i, /\b(how fast|how soon|when|one[- ]line status|next update|report|commit|promise)\b/i],
    exclude: [/\b(ship|ship first|users?|customers?|feature|error messages?|better error|saas|product)\b/i],
    output: "I do not know the exact status yet, so I would not promise a time. I would ask for one concrete update now, then only give the next update when something actually changes.",
    reasoning: "Immediate process-safe status update response",
    confidence: 0.88,
  },
  {
    id: "immediate:meeting-api-schema-unblock",
    priority: 607,
    category: "meeting_process",
    include: [/\bapi response schema\b|\bresponse schema from backend\b|\bschema from backend\b/i],
    output: "Let's use a mock schema for now, write down the assumptions, and replace it once backend confirms the real response shape.",
    reasoning: "Immediate meeting API schema unblock response",
    confidence: 0.9,
  },
  {
    id: "immediate:meeting-progress-update-next-step",
    priority: 606,
    category: "meeting_process",
    include: [/\bprogress update\b|\bquick update\b|\bwhat should i say\b.*\b(progress|update)\b/i],
    output: "I finished the DynamoDB table and mocked the API response. Next I'm testing the main flow and checking what still breaks before the demo.",
    reasoning: "Immediate meeting progress update with next step",
    confidence: 0.9,
  },
  {
    id: "immediate:unclear-requirements-tradeoff",
    priority: 605,
    category: "meeting_process",
    include: [/\b(requirements?|unclear|scope|trade[- ]?off)\b/i, /\b(public health|project|requirements?|scope|unclear requirements)\b/i],
    exclude: [/\b(gossip|rumou?r|hearsay|honesty|team trust|protecting boundaries|reporting|who do you tell|what do you say|verbatim|rag|retrieval|generation|pipeline|embedding|indexing|sensitive artifacts?|sensitive data(?:sets?)?|datasets?|retention|chain[-\s]?of[-\s]?custody|lineage|provenance|what exactly changes|exactly changes|change list|demo timeline|deliverables? are guaranteed)\b/i],
    output: "When requirements are unclear, the trade-off is speed versus correctness. I would freeze the smallest safe version, write the assumptions down, and ask for confirmation before building more.",
    reasoning: "Immediate unclear-requirements trade-off answer",
    confidence: 0.9,
  },
  {
    id: "immediate:tradeoff-pushback-boundary",
    priority: 604,
    category: "meeting_process",
    include: [/\b(pushback|don'?t buy|doesn'?t buy|disagree|says?\s+no|someone says\s+no)\b/i, /\b(user side|user impact|deadline|timeline|persuade|trade[- ]?offs?|smaller working|testable)\b/i],
    output: "If they still push back, I would set a boundary: we should not commit to the bigger trade-off without evidence. I would offer one smaller test, name the owner, and decide from user impact, time, and risk.",
    reasoning: "Immediate trade-off pushback boundary",
    confidence: 0.9,
  },
  {
    id: "immediate:hard-bug-process-agreement",
    priority: 503,
    category: "tech_process",
    include: [/\b(hardest|hard|difficult|tricky)\b/i, /\b(bug|issue|problem|debug)\b/i, /\b(reproduc|trace|end[-\s]?to[-\s]?end|request id|logs?|start by|process|how do you debug)\b/i],
    exclude: [/\b(tell me about a time|describe a time|give me an example|real example|what was your|your hardest|you fixed)\b/i],
    output: "Yes, that is the right process: reproduce it, isolate the failing layer, trace one request end to end, then compare logs and inputs before changing code.",
    reasoning: "Immediate concise hard-bug process agreement",
    confidence: 0.9,
  },
  {
    id: "immediate:scope-milestone-writing",
    priority: 502,
    category: "meeting_process",
    include: [/\b(milestones?|included|excluded|acceptance criteria)\b/i, /\b(in writing|spell|scope|renewal|demo)\b/i],
    output: "I would write it as three parts: included work, excluded work, and acceptance criteria. Then add milestone dates and one owner for each item so we can verify what is actually done.",
    reasoning: "Immediate scope milestone writing answer",
    confidence: 0.9,
  },
];
