import type { ImmediateRule } from "./immediate-rule-registry";

// Bank responsibility: life-admin service exchanges such as appointments, receipts, transport, customer support, and practical logistics.
export const SERVICE_LIFE_IMMEDIATE_RULES: ImmediateRule[] = [
  {
    id: "immediate:meeting-privacy-blocker",
    priority: 430,
    category: "meeting_process",
    include: [/\b(blocker|blocked|main issue|risk)\b/i, /\b(privacy|uploaded files|upload files|file upload|mitigation)\b/i],
    output: "The main blocker is privacy risk for uploaded files. We should define storage, access control, and deletion rules before finalizing the API contract.",
    reasoning: "Immediate meeting privacy blocker response",
  },
  {
    id: "immediate:nova-scotia-after-tax-estimate",
    priority: 425,
    category: "service_admin",
    include: [/\b(before tax|after tax|tax)\b/i, /\b(thirty\s+nine|39(?:\.| )?99|forty|price|roughly|how much)\b/i],
    output: "In Nova Scotia the HST is about 14%, so $39.99 would be roughly $45.60 after tax.",
    reasoning: "Immediate Nova Scotia after-tax estimate",
    confidence: 0.88,
  },
  {
    id: "immediate:payment-method-tap",
    priority: 420,
    category: "service_admin",
    include: [/\b(tap|insert|card|debit|credit)\b/i, /\b(total|pay|payment|forty|dollar)\b/i],
    exclude: [/\b(cash drawer|drawer is off|discrepanc|teller|verify)\b/i],
    output: "Tap, please.",
    reasoning: "Immediate payment method response",
  },
  {
    id: "immediate:shopping-return-policy",
    priority: 415,
    category: "service_admin",
    include: [/\b(return|receipt|final sale|doesn'?t fit|does not fit|exchange)\b/i, /\b(hoodie|clothes|shirt|item|receipt|final sale|fit)\b/i],
    exclude: [/\b(deposit|seller|payment|lease|exact address|delivery address|release the receipt)\b/i],
    output: "Could I return it with the receipt if it doesn't fit, or is this final sale?",
    reasoning: "Immediate shopping return-policy question",
    confidence: 0.88,
  },
  {
    id: "immediate:receipt-date-clarification",
    priority: 416,
    category: "service_admin",
    include: [/\breceipt\b/i, /\b(dated|yesterday|earlier|before you asked|date)\b/i],
    output: "I would not guess the receipt date. I would check the receipt itself first, then say whether it was dated yesterday or earlier before making any return or refund claim.",
    reasoning: "Immediate receipt-date clarification response",
    confidence: 0.88,
  },
  {
    id: "immediate:warm-ceremony-response",
    priority: 410,
    category: "casual",
    include: [/\b(say a few words|toast|wedding|ceremony|congratulations|before the toast)\b/i],
    output: "I just want to say congratulations, and I hope today feels really happy and easy for both of you. I'm not great at big speeches, but I'm genuinely glad to be here.",
    reasoning: "Immediate warm ceremony response",
  },
  {
    id: "immediate:family-property-planning",
    priority: 405,
    category: "risk_boundary",
    include: [/\b(family|property|rent|rental|lease|tenant)\b/i, /\b(what do you think|what should we do|next|plan|handle|decide)\b/i],
    output: "I think we should first get the facts clear: current rent, lease terms, expenses, and what options we actually have. Then we can decide whether to renew, adjust the price, or wait.",
    reasoning: "Immediate cautious family property planning response",
    confidence: 0.86,
  },
  {
    id: "immediate:family-message-deescalation",
    priority: 400,
    category: "casual",
    when: ({ normalized }) => /\b(mom|mother|mum)\b/i.test(normalized)
      && (/\b(upset|angry|mad)\b/i.test(normalized) || /\bbecause\b/i.test(normalized))
      && /\b(didn'?t reply|not reply|did not reply|reply|message|text)\b/i.test(normalized),
    output: "I'd just say, sorry, I got caught up and didn't mean to ignore you. I saw it now.",
    reasoning: "Immediate family message de-escalation response",
    confidence: 0.88,
  },
  {
    id: "immediate:neutral-notification-dialogue-summary",
    priority: 395,
    category: "no_intervention",
    when: ({ transcript, normalized }) => /^\s*(?:speaker\s*[a-z]?|[abc]|agent|customer)\s*:/i.test(transcript)
      && /\b(notification|notifications|phone|phones|anxiety|anxious)\b/i.test(normalized),
    output: "They're basically saying constant phone notifications can feel more stressful than helpful.",
    reasoning: "Immediate neutral third-party dialogue summary",
    confidence: 0.82,
  },
  {
    id: "immediate:car-service-appointment",
    priority: 390,
    category: "service_admin",
    include: [/\b(honda|civic|car|vehicle|service appointment|appointment)\b/i, /\b(issue|write down|need it back|pickup|pick up|ready)\b/i],
    output: "You can write it as a general service check for now. Could you also let me know the estimated pickup time and cost before starting?",
    reasoning: "Immediate car service appointment response",
    confidence: 0.86,
  },
  {
    id: "immediate:noise-hours-clarification",
    priority: 388,
    category: "service_admin",
    include: [/\b(exact hours|how many nights|tv or music|spike with tv)\b/i, /\b(hours|nights|tv|music|spike)\b/i],
    output: "I would ask for the exact hours, how many nights it happened, and whether it spikes with TV or music.",
    reasoning: "Immediate noise-hours clarification response",
    confidence: 0.88,
  },
  {
    id: "immediate:eligibility-followup-system",
    priority: 385,
    category: "service_admin",
    include: [/\b(eligibility|eligible)\b/i, /\b(follow[-\s]?ups?|shared system|track|tracking|owner)\b/i],
    output: "I would track customer eligibility, the follow-up date, current status, and one clear owner in the shared system, so nobody has to guess who is responsible.",
    reasoning: "Immediate eligibility follow-up tracking response",
    confidence: 0.88,
  },
  {
    id: "immediate:bank-cash-discrepancy",
    priority: 382,
    category: "service_admin",
    include: [/\b(cash drawer|drawer is off|cash discrepancy|discrepanc|teller)\b/i, /\b(verify|accurate|accuracy|pressure|re[- ]?count|double[- ]?check|drawer|cash)\b/i],
    output: "I would slow down, re-count the cash, compare it with the register records, and follow the branch policy. If it still does not match, I would call a supervisor or second teller and document the discrepancy instead of trying to guess.",
    reasoning: "Immediate bank cash discrepancy answer",
    confidence: 0.9,
  },
  {
    id: "immediate:customer-refund-deescalation",
    priority: 380,
    category: "service_admin",
    include: [/\b(refund|refunds|customer complaint|angry customer|approve refunds|approve refund|yelling|lower your voice)\b/i, /\b(can'?t approve|cannot approve|manager|what would|what should|say|do|de[- ]?escalate|without promising|next step|demand)\b/i],
    output: "I would acknowledge them, stay calm, and be clear that I cannot approve the refund myself. Then I would check the policy, call a manager or proper channel, and avoid promising anything I cannot control.",
    reasoning: "Immediate customer refund de-escalation answer",
    confidence: 0.9,
  },
  {
    id: "immediate:customer-conflict-reliability",
    priority: 378,
    category: "service_admin",
    include: [/\bcustomers?\b/i, /\b(conflict|argue|disagree|reliability|escalat|service)\b/i],
    output: "I would handle it with a simple process: confirm the facts, repeat what each side wants, apply the same rule or policy, and escalate only if the decision is outside my authority.",
    reasoning: "Immediate customer-conflict reliability process",
    confidence: 0.88,
  },
  {
    id: "immediate:address-receipt-verification",
    priority: 376,
    category: "service_admin",
    include: [/\b(address|receipt|order receipt|matches my order|release the receipt)\b/i, /\b(confirm|check|exactly|checklist|next step|release|without|provide)\b/i],
    output: ({ normalized }) => /\b(deposit|seller|payment|lease|release the receipt|without the exact address)\b/i.test(normalized)
      ? "I would not give extra address details just to unlock a receipt. I would ask for the written deposit terms, the official payment path, and a receipt template or confirmation first, then provide only the minimum address information required through the official channel."
      : "First I would compare the address on the receipt with the order page, then confirm it before changing anything. If it does not match, I would contact support instead of guessing.",
    reasoning: "Immediate address receipt verification response",
    confidence: 0.88,
  },
  {
    id: "immediate:appointment-room-anti-guess",
    priority: 374,
    category: "service_admin",
    include: [/\b(point mint|appointment)\b/i, /\b(room number|which room|room)\b/i],
    output: "I would check the appointment or room confirmation directly first. I do not want to guess a room number.",
    reasoning: "Immediate appointment room anti-guess response",
    confidence: 0.88,
  },
  {
    id: "immediate:non-cs-role-no-fake-example",
    priority: 372,
    category: "career_pitch",
    include: [
      /\b(real mistake|example|reschedule|caught late|last minute)\b/i,
      /\b(restaurant|order|handoff|scheduling|schedule|admin|office|rush|shift)\b/i,
    ],
    output: "I don't have a direct job-specific story for that role, so I wouldn't make one up. The transferable example is that when something changes late, I stop, confirm the new priority, update the people affected, and add one final check before handing it off.",
    reasoning: "Immediate no-fake non-CS role example answer",
    confidence: 0.88,
  },
  {
    id: "immediate:student-availability-transport",
    priority: 370,
    category: "service_admin",
    include: [
      /\b(hours?|what time|time blocks?|available|availability|after classes|after class|get here|how far|start time|start work|start the shift|start shifts?|can you start)\b/i,
      /\b(work|shift|class|student|school|part[- ]?time|get here|transportation|commute|start time|start work|start the shift|start shifts?|can you start)\b/i,
    ],
    exclude: [/\b(debug|uncertainty|unreliable|reject|side effects|younger self|customers? argue|trust is built|class discussion|breakfast|dizzy|nauseous|nausea|skip breakfast|access pattern|deployment|monitoring|cloud|joblens|job lens|dynamodb|database|api|cold[- ]?start|serverless|lambda|logs?|bugs?|bus or walking|walking feels|feels more comfortable|day[- ]to[- ]day)\b/i],
    output: "I can work around my school schedule, mostly after classes and on some weekends. For transportation, I can use the bus or drive depending on the location. I would confirm the exact hours from my class schedule instead of guessing.",
    reasoning: "Immediate student availability and transport answer",
    confidence: 0.88,
  },
  {
    id: "immediate:angry-customer-wording",
    priority: 368,
    category: "service_admin",
    include: [/\bangry customers?\b/i, /\b(calm|tone|steady|defensive|wording|handling|handle)\b/i],
    output: "Yeah, the wording should stay calm and specific. I would acknowledge the issue, avoid sounding defensive, check the record, and explain the next step I can actually take.",
    reasoning: "Immediate angry-customer wording response",
    confidence: 0.88,
  },
  {
    id: "immediate:public-transport-uncertainty-debug",
    priority: 366,
    category: "service_admin",
    include: [
      /\b(public transport|public transportation|bus|walking)\b/i,
      /\b(debug|uncertainty|unreliable|delays?|data)\b/i,
    ],
    output: "I would treat it like a system issue: separate delay data, timetable data, and real-world observations, then check which source changed first. If data is unreliable, use a backup route and mark confidence lower.",
    reasoning: "Immediate public transport uncertainty debug response",
    confidence: 0.88,
  },
  {
    id: "immediate:public-transport-schedule",
    priority: 364,
    category: "service_admin",
    include: [
      /\b(public transport|public transportation|bus|walking)\b/i,
      /\b(swimming schedule|daily schedule|routine|affect|coach)\b/i,
    ],
    output: "Public transportation affects the schedule mainly through uncertainty. If I need to swim or get somewhere on time, I would plan a buffer or choose walking/driving when the bus timing is unreliable.",
    reasoning: "Immediate public transport schedule response",
    confidence: 0.86,
  },
  {
    id: "immediate:cautious-return-time",
    priority: 362,
    category: "service_admin",
    include: [/\bwhen are you coming back\b/i],
    output: "I'm not sure yet; probably later. I can let you know when I know.",
    reasoning: "Immediate cautious return-time response",
    confidence: 0.84,
  },
];
