import type { ImmediateRule } from "./immediate-rule-registry";

// Bank responsibility: conversation mechanics, short acknowledgements, handoffs, and output-shape-safe replies.
export const CONVERSATION_IMMEDIATE_RULES: ImmediateRule[] = [
  {
    id: "immediate:minimal-acknowledgement-filler",
    priority: 240,
    category: "no_intervention",
    action: "silent",
    include: [/^\s*(?:mm+[-\s]?hmm+|mhm+|uh[-\s]?huh|yeah|yep|okay|ok)[.!?\s]*$/i],
    when: ({ signals }) => signals.likelyNoDisplay,
    output: "",
    reasoning: "Silent minimal acknowledgement without stale-context continuation",
    confidence: 0.82,
  },
  {
    id: "immediate:attendance-present",
    priority: 235,
    category: "casual",
    include: [/^\s*present[.!?\s]*$/i],
    output: "Present.",
    reasoning: "Immediate attendance response",
  },
  {
    id: "immediate:continuation-fragment",
    priority: 230,
    category: "casual",
    include: [/^\s*(?:and|so|then)[.!?\s]*$/i],
    output: "Yeah, go on.",
    reasoning: "Immediate minimal response for continuation fragment",
    confidence: 0.82,
  },
  {
    id: "immediate:meeting-almost-ready",
    priority: 225,
    category: "meeting_process",
    include: [/^\s*(?:[A-Z]\s*:\s*)?(?:uh\s+|um\s+)?almost[.!?\s]*$/i],
    output: "Almost. Give me one minute, then next I can share my part.",
    reasoning: "Immediate meeting almost-ready response with next step",
    confidence: 0.84,
  },
  {
    id: "immediate:single-name-fragment",
    priority: 220,
    category: "casual",
    exclude: [/^\s*(?:hello|hi|hey|thanks?|thank\s+you|okay|ok|yeah|yep|fine)\s*[.!?]*\s*$/i],
    when: ({ transcript }) => /^\s*[A-Z][a-zA-Z'-]{2,24}[.!?\s]*$/.test(transcript),
    output: "I heard the name, but I don't have enough context yet.",
    reasoning: "Immediate single-name fragment response without forced follow-up",
    confidence: 0.82,
  },
  {
    id: "immediate:wrong-number",
    priority: 215,
    category: "casual",
    include: [/\bwrong number\b/i],
    output: "Sorry about that. You must have the wrong number.",
    reasoning: "Immediate wrong-number response without forced follow-up",
    confidence: 0.84,
  },
  {
    id: "immediate:casual-doctor-greeting",
    priority: 210,
    category: "casual",
    include: [/^\s*hey,\s*doctor[.!?\s]*$/i],
    output: "Hey, good morning.",
    reasoning: "Immediate casual doctor greeting without forced follow-up",
    confidence: 0.82,
  },
  {
    id: "immediate:unclear-fragment-clarification",
    priority: 205,
    category: "casual",
    includeAny: [/\bname and the\b/i, /\bgargle\b/i],
    output: "Sorry, I didn't catch that clearly.",
    reasoning: "Immediate unclear fragment response without forced follow-up",
    confidence: 0.82,
  },
  {
    id: "immediate:duplicated-audio-clarification",
    priority: 195,
    category: "asr_correction",
    include: [/\bdid i just get two people\b/i],
    output: "No, just one person here. Maybe the audio doubled.",
    reasoning: "Immediate duplicated-audio clarification without forced follow-up",
    confidence: 0.84,
  },
  {
    id: "immediate:handoff-no-action",
    priority: 190,
    category: "no_intervention",
    include: [/\bthere you go\b/i],
    output: "That is just a handoff; no action needed yet.",
    reasoning: "Immediate handoff response without forced follow-up",
    confidence: 0.82,
  },
];
