import type { ImmediateRule } from "./immediate-rule-registry";

export const PERSONAL_IMMEDIATE_RULES: ImmediateRule[] = [
  {
    id: "immediate:genshin-exact-title-grounding",
    priority: 255,
    category: "casual",
    when: ({ normalized }) => (
      /\bgenshin\b/i.test(normalized)
      || (/\b(soundtrack|track title|track name)\b/i.test(normalized)
        && /\b(song|songs|music|genshin|exact|title|pick one)\b/i.test(normalized))
    ) && /\b(name|specific|exact|title|pick one|name two|no more|official)\b/i.test(normalized),
    output: "I would not fake official track titles if I am not sure. Safely, I would say Inazuma battle music and Liyue or Mondstadt ambient music are the styles I like, then verify the exact names later.",
    reasoning: "Immediate Genshin exact-title grounding guard",
    confidence: 0.88,
  },
  {
    id: "immediate:grounded-media-specificity",
    priority: 235,
    category: "casual",
    when: ({ normalized }) => (
      /\b(which|what)\b/i.test(normalized)
      || /\b(name one example|specific scene|specific character|describe a scene|remember well)\b/i.test(normalized)
    )
      && /\b(anime|movies?|films?|tv shows?|scene|videos?)\b/i.test(normalized)
      && !/\b(dream|turn .* into a movie|scope|timeline|track titles?|timestamps?|allowed to reference|verbatim|genshin|soundtrack|media framing|politeness|adverts?|advertisements?|on[- ]scene evidence|verifiable sources?|support that claim)\b/i.test(normalized),
    output: "I watch anime and videos more casually, so I would not force a specific title if I cannot clearly remember one. What I usually like is atmosphere, music, story, and characters that make the world feel immersive.",
    reasoning: "Immediate grounded media-specificity guard",
    confidence: 0.88,
  },
  {
    id: "immediate:grounded-social-style",
    priority: 205,
    category: "casual",
    include: [/\b(talk with others|talk to others|talking with others)\b/i],
    output: "I am okay with one-on-one conversations, but I do not like big groups or forced socializing.",
    reasoning: "Immediate grounded social-style response",
    confidence: 0.86,
  },
  {
    id: "immediate:grounded-recent-friends",
    priority: 200,
    category: "casual",
    include: [/\b(new friends?|made any new friends?)\b/i, /\brecently|lately|these days\b/i],
    output: "Not really recently. I have mostly been busy with school and staying in my usual routine.",
    reasoning: "Immediate grounded recent-friends response",
    confidence: 0.86,
  },
  {
    id: "immediate:grounded-childhood-active-to-quiet",
    priority: 195,
    category: "casual",
    include: [/\b(child|kid|little|younger)\b/i, /\b(quiet|active|lively|naughty|personality|changed|became quieter|grew older)\b/i],
    output: "When I was very young, I was actually pretty lively and naughty, not quiet. I became much quieter later, probably around middle school, and that change felt quite sudden.",
    reasoning: "Immediate grounded childhood active-to-quiet answer",
  },
  {
    id: "immediate:childhood-change-new-environment",
    priority: 193,
    category: "casual",
    include: [/\b(childhood self|childhood|younger self|as a child)\b/i, /\b(change|changed|shipping route|route)\b/i],
    output: "I changed quite a bit. I became more cautious after growing up and moving into a new environment, even though my interests did not completely change.",
    reasoning: "Immediate childhood change and new-environment answer",
    confidence: 0.88,
  },
  {
    id: "immediate:caution-before-interests",
    priority: 192,
    category: "casual",
    include: [/\b(caution|cautious)\b/i, /\b(interests?|changed first|what changed first|new environment)\b/i],
    output: "The caution changed first. My interests stayed more similar, but the new environment made me quieter and more careful.",
    reasoning: "Immediate caution-before-interests answer",
    confidence: 0.88,
  },
  {
    id: "immediate:grounded-study-place",
    priority: 190,
    category: "casual",
    include: [/\b(favorite|favourite|best)\b/i, /\b(place to study|study place|where to study|study)\b/i],
    output: "I do not really have a favorite study place. Usually I just need somewhere quiet, with internet, and not too many distractions.",
    reasoning: "Immediate grounded study-place response",
    confidence: 0.88,
  },
  {
    id: "immediate:grounded-travel-preference",
    priority: 185,
    category: "casual",
    include: [/\b(which place|where)\b/i, /\b(want to visit|would like to visit|would you like to visit|want to travel|travel there|visit someday|travel someday)\b/i],
    output: "I would probably choose Japan, mainly because of games, anime, music, food, and maybe learning Japanese. I have not been there yet, so I would keep it as a future plan, and I would prefer going with other people instead of travelling alone.",
    reasoning: "Immediate grounded travel-preference response",
  },
  {
    id: "immediate:airport-bus-versus-walking",
    priority: 180,
    category: "casual",
    include: [/\b(bus|walking|walk)\b/i, /\b(airport|travel|route|comfortable|unpack)\b/i],
    output: "For airport travel, bus is usually more comfortable if there is luggage or a longer distance. Walking only makes sense for a short, clear route with light bags and good weather.",
    reasoning: "Immediate airport bus-versus-walking answer",
    confidence: 0.88,
  },
  {
    id: "immediate:travel-detail-anti-invention",
    priority: 175,
    category: "casual",
    include: [/\b(exact people|who would you travel with|who would you go with|meet them|departure|airport|where would you meet|exact route|exact transport|transport between|between each city|specific way|by plane|by train|by car|which station|arrival in|arrive in|step by step)\b/i, /\b(travel|trip|visit|departure|go with|friends|group|route|transport|city|cities|japan|tokyo|kyoto|station)\b/i],
    exclude: [/\b(bus|walking|walk|comfortable)\b/i],
    output: "I do not have exact people or a real route planned yet. Broadly, I would fly there and use trains inside Japan, but I would frame it as a future idea, not a fixed trip.",
    reasoning: "Immediate travel-detail anti-invention response",
  },
  {
    id: "immediate:grounded-culture-place",
    priority: 170,
    category: "casual",
    include: [/\b(cultural place|country|place to visit|travel culture)\b/i, /\b(learn|like|would|want|describe|there|visit|travel)\b/i],
    output: "Probably Japan, mainly because I like games, anime, music, and maybe learning Japanese. I have not been there, so I would frame it as curiosity, not a travel story.",
    reasoning: "Immediate grounded culture-place response",
    confidence: 0.88,
  },
  {
    id: "immediate:grounded-mentor-admiration",
    priority: 165,
    category: "casual",
    include: [/\b(person|someone|people)\b/i, /\b(admire|influenced|influence|mentor|helped you|helped me|changed your life|changed your direction)\b/i],
    output: "One person I would talk about is Mr. Jiang. He knew my mother and helped me during the study-abroad transition, including recommendation support and practical advice. I admire him because his help changed my direction when I did not really know how to move forward.",
    reasoning: "Immediate grounded mentor admiration response",
  },
  {
    id: "immediate:grounded-mentor-follow-up",
    priority: 160,
    category: "casual",
    include: [/\b(specific example|what exactly|what did he|what did that person|how did he|how did that person|what lesson)\b/i, /\b(help|helped|advice|recommendation|study abroad|mentor|influence|admire|important person)\b/i],
    output: "A specific example is that he helped with recommendation support and gave advice when I was trying to study abroad. That mattered because without that kind of guidance, I might not have been able to make the transition to Canada smoothly.",
    reasoning: "Immediate grounded mentor follow-up response",
  },
  {
    id: "immediate:grounded-view-memory",
    priority: 155,
    category: "casual",
    include: [/\bunforgettable view\b|\bseen .* view\b|\bbeautiful view\b/i],
    output: "Not really. I do not have one unforgettable view that clearly stands out. I usually like quieter views more than crowded tourist places.",
    reasoning: "Immediate grounded view-memory response",
    confidence: 0.88,
  },
  {
    id: "immediate:grounded-favourite-teacher",
    priority: 150,
    category: "casual",
    include: [/\b(favou?rite|favorite)\s+(teacher|professor|instructor)\b/i],
    output: "I do not really have one specific favourite teacher. I usually remember teachers who explain things clearly and do not make the class too stressful.",
    reasoning: "Immediate grounded favourite-teacher response",
    confidence: 0.88,
  },
  {
    id: "immediate:grounded-teaching-career",
    priority: 145,
    category: "casual",
    include: [/\b(work as|be|become)\s+a\s+teacher\b|\bwould you like to teach\b|\bteaching\b.*\byour thing\b/i],
    output: "Not really. I respect teaching, but I prefer building systems where I can focus quietly and solve practical problems.",
    reasoning: "Immediate grounded teaching-career response",
    confidence: 0.88,
  },
  {
    id: "immediate:misunderstanding-work-money",
    priority: 140,
    category: "casual",
    include: [/\b(misunderstood|misread|message gets twisted|interpreted wrong)\b/i, /\b(work|money|budget|decision|communication|how do you say)\b/i],
    output: "I would say people fear being misunderstood because one unclear sentence can make their judgment look worse than it is, especially around money or work decisions. The safer move is to state the context, the reason, and the next step clearly.",
    reasoning: "Immediate misunderstanding work-money framing",
  },
  {
    id: "immediate:grounded-prize",
    priority: 135,
    category: "casual",
    include: [/\b(prize|award)\b/i, /\b(received|won|got|describe|talk about|have)\b/i],
    output: "I have not won any big prize that I would confidently talk about. I am more proud of finishing real projects than receiving awards.",
    reasoning: "Immediate grounded prize response",
    confidence: 0.88,
  },
  {
    id: "immediate:compact-traditional-food",
    priority: 130,
    category: "casual",
    include: [/\btraditional food|traditional festival|special event\b/i, /\b(country|china|chinese)\b/i],
    output: "For China, I would probably say zongzi during Dragon Boat Festival. It is sticky rice wrapped in bamboo leaves, sometimes with meat or red bean.",
    reasoning: "Immediate compact traditional-food response",
    confidence: 0.86,
  },
  {
    id: "immediate:grounded-fishing",
    priority: 125,
    category: "casual",
    include: [/\bfishing|go fishing|gone fishing|went fishing\b/i],
    output: "I have not really gone fishing much. I like the idea of quiet outdoor stuff, but most of my free time is still games, anime, or staying inside.",
    reasoning: "Immediate grounded fishing response",
    confidence: 0.86,
  },
  {
    id: "immediate:grounded-primary-school-teacher-contact",
    priority: 120,
    category: "casual",
    include: [/\bprimary school teachers?\b/i, /\bstill in touch|keep in touch|contact\b/i],
    output: "No, not really. I would keep that answer short.",
    reasoning: "Immediate grounded primary-school-teacher contact response",
    confidence: 0.86,
  },
];
