import type { ImmediateRule } from "./immediate-rule-registry";

// Bank responsibility: evidence, provenance, audit, source quality, privacy ownership, and anti-fabrication risk controls.
export const RISK_EVIDENCE_IMMEDIATE_RULES: ImmediateRule[] = [
  {
    id: "immediate:risk-config-escalation-knobs",
    priority: 539,
    category: "risk_boundary",
    include: [
      /\b(provenance|source log|risk config|risk score|misinformation)\b/i,
      /\b(log|audit|config|risk|provenance|source|threshold|review)\b/i,
      /\b(config knobs?|escalation timing|threshold|control)\b/i,
    ],
    output: "The config knobs would be source trust level, claim severity, confidence score, user exposure, and repeat frequency. Those control whether we just log it, slow it down, or require human review.",
    reasoning: "Immediate risk config escalation knobs response",
    confidence: 0.9,
  },
  {
    id: "immediate:provenance-audit-process",
    priority: 538,
    category: "risk_boundary",
    include: [
      /\b(provenance|source log|risk config|risk score|misinformation)\b/i,
      /\b(log|audit|config|risk|provenance|source|threshold|review)\b/i,
    ],
    exclude: [/\b(config knobs?|escalation timing|threshold|control)\b/i],
    output: "I would log provenance first: source, timestamp, confidence, and who used it. Then I would throttle or require review when the risk score is high, instead of treating every claim the same.",
    reasoning: "Immediate provenance audit process response",
    confidence: 0.88,
  },
  {
    id: "immediate:health-misinformation-source-evidence",
    priority: 537,
    category: "risk_boundary",
    include: [
      /\b(misinformation|health claims?|false claims?)\b/i,
      /\b(which sources?|prove|evidence|credible|claims?)\b/i,
    ],
    output: "For health misinformation, I would rely on official public-health sources, peer-reviewed papers, and reputable medical organizations. I would not use one viral post or anecdote as evidence.",
    reasoning: "Immediate health misinformation source response",
    confidence: 0.88,
  },
  {
    id: "immediate:cybersecurity-useless-collection-risk",
    priority: 536,
    category: "risk_boundary",
    include: [
      /\b(cybersecurity|security)\b/i,
      /\b(collect useless things|useless things|happy gateway|gateway risk|low[- ]cost collecting)\b/i,
    ],
    output: "In cybersecurity, useless collection becomes risky because every extra log, file, or account increases the attack surface. The trade-off is future usefulness versus data exposure, so the next step is retention rules and least-privilege access.",
    reasoning: "Immediate cybersecurity useless-collection risk response",
    confidence: 0.88,
  },
  {
    id: "immediate:health-misinformation-sharing-boundary",
    priority: 534,
    category: "risk_boundary",
    include: [
      /\b(health misinformation|sharing health|diagnosis|medical details)\b/i,
      /\b(dead line|deadline|share|social media|personal details)\b/i,
    ],
    output: "My boundary is simple: do not share personal medical details, and do not repost health claims unless a reliable source supports them. If unsure, say I need to verify it first.",
    reasoning: "Immediate health misinformation sharing boundary",
    confidence: 0.9,
  },
  {
    id: "immediate:source-safe-kubernetes-environmental",
    priority: 533,
    category: "risk_boundary",
    include: [
      /\b(kubernetes|environmental)\b/i,
      /\b(specific|which project|measurable|harm|disruption|not docker|using kubernetes)\b/i,
    ],
    exclude: [/\b(stores?|delayed items?|substitutes?|old supply chain disruption news)\b/i],
    output: "I would not name a specific project without a source. I would explain the mechanism instead: Kubernetes can add waste if workloads are over-provisioned, but measurable environmental harm needs real data.",
    reasoning: "Immediate source-safe Kubernetes environmental response",
    confidence: 0.88,
  },
  {
    id: "immediate:source-safe-supply-chain-case",
    priority: 532,
    category: "risk_boundary",
    include: [
      /\b(supply[- ]chain|environmental harm|shipping|case study)\b/i,
      /\b(cite|case study|real project|which project|shows?|harm)\b/i,
    ],
    output: "I cannot reliably cite a specific case study from memory. I would say the right evidence would be before-and-after emissions, rerouting distance, delays, and waste, then cite an actual logistics report.",
    reasoning: "Immediate source-safe supply-chain case response",
    confidence: 0.88,
  },
  {
    id: "immediate:source-safe-japan-benchmark",
    priority: 531,
    category: "risk_boundary",
    include: [
      /\b(japan[- ]specific|incident data|benchmarks?)\b/i,
      /\b(which|what|data|benchmark|incident)\b/i,
    ],
    output: "I do not have Japan-specific incident data offhand, so I would not invent a number. I would check official reports or credible datasets first, then compare against a clear benchmark.",
    reasoning: "Immediate source-safe Japan benchmark response",
    confidence: 0.88,
  },
  {
    id: "immediate:risk-evidence-owner",
    priority: 530,
    category: "risk_boundary",
    when: ({ normalized }) => {
      const ownerEvidence = /\b(logs?|documents?|data scheme|scheme owner|who owns)\b/i.test(normalized);
      const directOwnerAsk = /\b(support those risks|support the risks|owns? the data|in writing)\b/i.test(normalized);
      const riskEvidenceAsk = /\b(specific risks?|highest risks?|in writing)\b/i.test(normalized)
        && /\b(risks?|evidence|supports?|highest)\b/i.test(normalized);
      return ownerEvidence && (directOwnerAsk || riskEvidenceAsk);
    },
    exclude: [/\b(code owner|data and code|code and data|ev news|sustainability metric|sustainable)\b/i],
    output: "In writing, I would name owners and evidence separately: logs from the app or platform, policy/source documents, user reports, and incident notes. The data scheme owner should be one named person or team, not everyone.",
    reasoning: "Immediate risk evidence owner response",
    confidence: 0.88,
  },
  {
    id: "immediate:highest-risks-evidence",
    priority: 528,
    category: "risk_boundary",
    include: [
      /\b(specific risks?|highest risks?|in writing)\b/i,
      /\b(risks?|evidence|supports?|highest)\b/i,
    ],
    exclude: [/\b(logs?|documents?|data scheme|scheme owner|who owns)\b/i],
    output: "In writing, I would rank the risks as privacy exposure, missing or biased data, and unclear ownership. Evidence should come from logs, source documents, user reports, and observed incidents, not just opinion.",
    reasoning: "Immediate highest risks evidence response",
    confidence: 0.88,
  },
  {
    id: "immediate:verifiable-source-evidence",
    priority: 527,
    category: "risk_boundary",
    include: [/\b(verifiable sources?|on[- ]scene evidence|evidence support|support that claim)\b/i],
    output: "I would separate sources from observations: use official records or credible reports as sources, then on-scene evidence like timestamps, photos, logs, witnesses, or raw notes to support the claim.",
    reasoning: "Immediate verifiable source evidence response",
    confidence: 0.88,
  },
  {
    id: "immediate:identity-verification-data-minimization",
    priority: 526,
    category: "risk_boundary",
    include: [
      /\b(verify identity|identity verification|prove identity)\b/i,
      /\b(data|minimi[sz]e|keeping more|unclear request)\b/i,
    ],
    output: "I would verify identity with the smallest reliable check: use an existing trusted channel, ask for one confirmation factor, and avoid storing extra copies unless there is a clear reason.",
    reasoning: "Immediate identity verification data-minimization response",
    confidence: 0.9,
  },
  {
    id: "immediate:immigration-limits-tradeoff",
    priority: 525,
    category: "risk_boundary",
    include: [
      /\b(immigration limits?|raise immigration|immigration policy)\b/i,
      /\b(trade[- ]?off|accept|why|limits?|raise)\b/i,
    ],
    output: "The argument for raising immigration limits is filling labor gaps and supporting growth. The trade-off is pressure on housing, healthcare, and processing capacity, so the policy only works if infrastructure scales too.",
    reasoning: "Immediate immigration limits trade-off response",
    confidence: 0.88,
  },
  {
    id: "immediate:sensitivity-scheme-documentation",
    priority: 524,
    category: "risk_boundary",
    include: [
      /\b(exact filters?|sensitivity scheme|documented)\b/i,
      /\b(filter|scheme|sensitivity|document|where|writing)\b/i,
    ],
    output: "I would write the filters as a short table: field name, sensitivity level, who can access it, and retention rule. Then the sensitivity scheme should live in the project doc, not just in someone's memory.",
    reasoning: "Immediate sensitivity scheme documentation response",
    confidence: 0.88,
  },
  {
    id: "immediate:uncertainty-schema-fields",
    priority: 523,
    category: "risk_boundary",
    include: [
      /\b(schema fields?|fields)\b/i,
      /\b(uncertainty|failure modes?|quantify|capture)\b/i,
    ],
    output: "I would capture uncertainty with fields like source, confidence, last_updated, missing_reason, and decision_status. The failure modes to quantify are stale data, missing data, wrong mapping, and low-confidence decisions.",
    reasoning: "Immediate uncertainty schema fields response",
    confidence: 0.88,
  },
  {
    id: "immediate:unknown-nimbus-anti-confirmation",
    priority: 522,
    category: "risk_boundary",
    include: [/\bnimbus\b/i, /\b(confirm|policy|which project|other project)\b/i],
    output: "I would not confirm Nimbus Cloud without checking. I would ask for the exact project name or source first, then use that name consistently.",
    reasoning: "Immediate unknown Nimbus project anti-confirmation",
    confidence: 0.9,
  },
  {
    id: "immediate:remote-learning-career-outcomes-evidence",
    priority: 521,
    category: "risk_boundary",
    include: [
      /\b(remote learning|covid)\b/i,
      /\b(assumptions?|risks?|outcomes?|in writing|list)\b/i,
      /\b(career outcomes?|evidence supports|specific outcomes?)\b/i,
    ],
    output: "For career outcomes, I would list internship access, communication confidence, portfolio quality, and networking as outcomes. Evidence would be grades, project output, applications, interview feedback, and participation data.",
    reasoning: "Immediate remote learning career outcomes evidence response",
    confidence: 0.88,
  },
  {
    id: "immediate:remote-learning-assumptions-risks",
    priority: 520,
    category: "risk_boundary",
    include: [
      /\b(remote learning|covid)\b/i,
      /\b(assumptions?|risks?|outcomes?|in writing|list)\b/i,
    ],
    exclude: [/\b(career outcomes?|evidence supports|specific outcomes?)\b/i],
    output: "For remote learning, my assumptions would be that access, motivation, and communication quality affect outcomes. The main risks are weaker engagement, uneven internet/device access, isolation, and harder feedback loops.",
    reasoning: "Immediate remote learning assumptions risks response",
    confidence: 0.88,
  },
  {
    id: "immediate:ai-summary-hallucination-audit-trail",
    priority: 519,
    category: "risk_boundary",
    include: [
      /\b(audit trail|hallucination|hallucinations|ai summarizes?|summary)\b/i,
      /\b(audit trail|hallucination|hallucinations|source|claim|verify|spot)\b/i,
    ],
    output: "For an AI summary audit trail, I would keep each claim tied to a source excerpt, timestamp, document or transcript ID, and confidence note. To spot hallucinations fast, check unsupported claims first and label anything without evidence.",
    reasoning: "Immediate AI-summary hallucination audit trail",
    confidence: 0.9,
  },
  {
    id: "immediate:field-purpose-retention-auditability",
    priority: 518,
    category: "risk_boundary",
    include: [
      /\b(field[-\s]?to[-\s]?purpose|purpose mappings?|retention schedules?|auditability|audit trail)\b/i,
      /\b(document|mapping|retention|schedule|audit|fields?|purpose)\b/i,
    ],
    exclude: [/\b(hallucination|hallucinations|ai summarizes?|summary|source claim|unsupported claims?)\b/i],
    output: "Yes. I would document each field, its purpose, retention schedule, owner, and approval status in one audit table, then review changes through the privacy or project owner before the demo.",
    reasoning: "Immediate field-purpose retention auditability response",
    confidence: 0.9,
  },
  {
    id: "immediate:privacy-safe-impact-evidence",
    priority: 517,
    category: "risk_boundary",
    include: [
      /\b(evidence|impact|outcome|metric|numbers?|proof|show)\b/i,
      /\b(without exposing|not expose|no raw|privacy[-\s]?safe|user data|individuals?|identifying data)\b/i,
    ],
    output: "Yes. I would point to aggregated evidence: before and after rates, counts, latency or completion time, and a short anonymized example if needed. I would avoid raw transcripts, names, exact locations, or anything that identifies one user.",
    reasoning: "Immediate privacy-safe impact evidence answer",
    confidence: 0.9,
  },
  {
    id: "immediate:data-controller-lawful-basis-process",
    priority: 516,
    category: "risk_boundary",
    include: [
      /\b(data controller|lawful basis|legal basis|basis for processing|audit trails?|audit logs?)\b/i,
      /\b(who|document|identify|lawful|legal|basis|audit|controller|project|demo|data)\b/i,
    ],
    output: "For this project, I would identify the controller as the team or organization deciding why the data is collected and how it is used. Then I would document purpose, data categories, lawful basis confirmed by the privacy or legal owner, access owner, retention window, and audit trail entries.",
    reasoning: "Immediate data-controller lawful-basis process",
    confidence: 0.9,
  },
  {
    id: "immediate:demo-data-lineage-documentation",
    priority: 515,
    category: "risk_boundary",
    include: [
      /\b(data lineage|lineage|provenance|consent basis|retention schedule)\b/i,
      /\b(data|demo|document|log|provenance|consent|retention|lineage)\b/i,
    ],
    output: "For demo data lineage, I would log provenance/source, timestamp, consent basis, retention schedule, owner, and access history. If any part is unknown, mark it unknown instead of treating the demo data as safe.",
    reasoning: "Immediate demo data-lineage documentation process",
    confidence: 0.9,
  },
  {
    id: "immediate:sensitive-artifact-retention-process",
    priority: 514,
    category: "risk_boundary",
    include: [
      /\b(sensitive artifacts?|sensitive data(?:sets?)?|residual data|data handling|retention|chain[-\s]?of[-\s]?custody|audit logs?|encryption[-\s]?at[-\s]?rest|post[-\s]?demo)\b/i,
      /\b(scope|demo|artifacts?|data(?:sets?)?|residual|handling|document|retention|encrypt|audit|access|logs?|privacy|chain)\b/i,
    ],
    output: "I would separate demo scope from sensitive data handling: collect only needed datasets or artifacts, set a short written retention window, restrict access, encrypt stored files, and log access or deletion. I would confirm owners before promising specifics.",
    reasoning: "Immediate sensitive-artifact retention process",
    confidence: 0.9,
  },
];
