import type { ImmediateRule } from "./immediate-rule-registry";

export const CASUAL_IMMEDIATE_RULES: ImmediateRule[] = [
  {
    id: "immediate:cooking-task-acknowledgement",
    priority: 930,
    category: "casual",
    include: [/\bwash\b/i, /\bvegetables?\b/i, /\bcut\b/i, /\bchicken\b/i],
    output: "Sure, I'll wash the vegetables and cut the chicken first.",
    reasoning: "Immediate task acknowledgement without unnecessary follow-up question",
  },
  {
    id: "immediate:fragment-acknowledgement-great",
    priority: 920,
    category: "casual",
    include: [/^\s*we'?re having great[.!?\s]*$/i],
    output: "Glad to hear that.",
    reasoning: "Immediate fragment acknowledgement without forced return question",
    confidence: 0.82,
  },
  {
    id: "immediate:grounded-sleep-routine",
    priority: 260,
    category: "casual",
    include: [/\b(what time|when)\b/i, /\b(sleep|go to bed|bedtime)\b/i],
    exclude: [/\b(lambda|function|cold start|aws)\b/i],
    output: "It depends, honestly. My sleep schedule is pretty irregular, especially when I have projects, so I often sleep late.",
    reasoning: "Immediate grounded sleep-routine response",
    confidence: 0.88,
  },
  {
    id: "immediate:driving-no-talk",
    priority: 250,
    category: "casual",
    include: [/\bi'?m driving\b|\bdriving,\s*buddy\b/i],
    output: "I'm driving, so I can't really talk right now.",
    reasoning: "Immediate driving response without forced return question",
    confidence: 0.86,
  },
  {
    id: "immediate:grounded-covid-undergrad",
    priority: 245,
    category: "casual",
    include: [/\b(covid|remote study|online class|online classes|undergrad|undergraduate)\b/i, /\b(change|affect|learn|experience|motivation|remote|online)\b/i],
    output: "COVID made my undergrad feel much less normal, because a lot of it became online and isolated. I learned that I had to manage myself more actively, especially by asking questions earlier and doing small practice instead of just watching lectures.",
    reasoning: "Immediate grounded COVID undergrad response",
    confidence: 0.88,
  },
  {
    id: "immediate:confidence-reframing",
    priority: 240,
    category: "casual",
    include: [/\bconfidence\b/i, /\b(know everything|not sure|next step|still trying)\b/i],
    output: "Yeah, that is closer to real confidence: admit uncertainty, then still take the next step.",
    reasoning: "Immediate confidence reframing response",
    confidence: 0.86,
  },
  {
    id: "immediate:clothes-confidence-cue",
    priority: 230,
    category: "casual",
    include: [/\b(shirt|outfit|wear|hoodie|formal)\b/i, /\b(confident|confidence|mood|braver|feel)\b/i],
    output: "Yeah, it can count. If a presentation shirt makes you feel more prepared, that confidence is real, but I would treat it as a small mood cue, not a guarantee.",
    reasoning: "Immediate clothes confidence cue response",
    confidence: 0.88,
  },
  {
    id: "immediate:honest-fiction-book-preference",
    priority: 225,
    category: "casual",
    include: [/\b(page[- ]?turner|mystery|thriller|gone girl|dragon tattoo|fast chapters|twisty)\b/i, /\b(book|read|try|want|craving|recommend|lighter)\b/i],
    output: "I have not read enough to pretend I know the exact book, but a fast mystery or thriller fits me better than heavy nonfiction. I would try it if it is not too slow.",
    reasoning: "Immediate honest fiction-book preference response",
    confidence: 0.88,
  },
  {
    id: "immediate:grounded-confidence-story",
    priority: 220,
    category: "casual",
    include: [/\b(confident|confidence)\b/i, /\b(feel|made|something|time|describe)\b/i],
    exclude: [/\b(clothes?|shirt|outfit|wear|hoodie|formal)\b/i],
    output: "Probably when I keep adjusting a UI and it finally looks good. It is not dramatic, but it makes me feel like, okay, I can actually build this.",
    reasoning: "Immediate grounded confidence-story response",
    confidence: 0.88,
  },
  {
    id: "immediate:rush-hour-joke",
    priority: 210,
    category: "casual",
    include: [/\byou must be joking\b/i],
    output: "Yeah, rush hour is painful. I would rather avoid driving then if I can.",
    reasoning: "Immediate grounded rush-hour joke response",
    confidence: 0.86,
  },
  {
    id: "immediate:honest-book-recommendation-boundary",
    priority: 205,
    category: "casual",
    when: ({ normalized }) => !(/\b(themes?)\b/i.test(normalized) && /\b(games?|anime|music|nonfiction|article|translate)\b/i.test(normalized))
      && !/\b(measurable|payoff|track|tracking|behavior change|behaviour change|metric|habit loop|takeaway|apply this week|actionable|without relying on ai)\b/i.test(normalized)
      && (
        /\b(serious nonfiction|nonfiction|book recommendation|good reads?|what about .*book|sapiens|atomic habits|meditations|man's search|thinking,? fast|left hand of darkness|war and peace)\b/i.test(normalized)
        || (
          /\b(try|readable|too heavy|book[- ]?ish|essay collection|short essay|collection|title)\b/i.test(normalized)
          && (/\b(book|essay|read|sapiens|denial of death|man without a country|left hand|darkness|country|anthropocene reviewed|braiding sweetgrass)\b/i.test(normalized) || /\*[^*]+\*/.test(normalized))
        )
      ),
    output: "Honestly, I do not read serious nonfiction that often, so I would not pretend to have a strong book list. I am more into games, anime, music, and online content, but I can talk about what kind of ideas sound interesting.",
    reasoning: "Immediate honest book-recommendation boundary",
    confidence: 0.88,
  },
  {
    id: "immediate:grounded-favorite-food",
    priority: 180,
    category: "casual",
    include: [/\b(favorite type of food|favourite type of food|favorite food|favourite food|what food do you like)\b/i],
    output: "Yeah, it is hard to pick one. I usually like Chinese food, fried chicken, curry, and malatang, depending on what is convenient.",
    reasoning: "Immediate grounded favorite-food response",
    confidence: 0.88,
  },
  {
    id: "immediate:atomic-habits-measurement",
    priority: 175,
    category: "casual",
    include: [/\batomic habits\b/i, /\b(measurable|payoff|track|behavior|behaviour|habit|takeaway|apply this week|actionable)\b/i],
    output: "The useful takeaway is to make the first step very small and visible. For this week, I would pick one behavior, define the trigger, and track whether I actually did it each day.",
    reasoning: "Immediate Atomic Habits measurement answer",
    confidence: 0.88,
  },
  {
    id: "immediate:grounded-shoes-open-topic",
    priority: 170,
    category: "casual",
    include: [/\b(shoes?|sidewalks?|potholes?|tourists?)\b/i, /\b(could talk|complain|what would they say|all energy)\b/i],
    output: "They would probably complain about rain, potholes, and too much walking. I would keep it simple, not turn it into a huge serious point.",
    reasoning: "Immediate grounded shoes open-topic response",
    confidence: 0.86,
  },
  {
    id: "immediate:honest-media-to-nonfiction-theme",
    priority: 165,
    category: "casual",
    include: [/\b(themes?)\b/i, /\b(games?|anime|music|nonfiction|article|translate)\b/i],
    output: "The themes I would connect to nonfiction are worldbuilding, technology, loneliness, identity, and how people adapt under pressure. Those fit me better than pretending I read a lot of serious books.",
    reasoning: "Immediate honest media-to-nonfiction theme response",
    confidence: 0.88,
  },
  {
    id: "immediate:grounded-home-food",
    priority: 150,
    category: "casual",
    include: [/\b(food feels like home|home food|ramen|home good)\b/i, /\b(home|cheap|predictable|economics|ramen|good)\b/i],
    output: "That makes sense. Food can feel like home when it is cheap, predictable, and easy to repeat. It is less about luxury and more about comfort and familiarity.",
    reasoning: "Immediate grounded home-food response",
    confidence: 0.86,
  },
  {
    id: "immediate:grounded-nickname",
    priority: 140,
    category: "casual",
    include: [/\b(nickname|what would you call yourself|call yourself)\b/i, /\b(why|psychological|documentation|choose|pick)\b/i],
    output: "I would choose something simple like Quiet Builder. It fits because I am not very loud socially, but I like quietly making systems work.",
    reasoning: "Immediate grounded nickname response",
    confidence: 0.86,
  },
  {
    id: "immediate:privacy-with-friends",
    priority: 130,
    category: "casual",
    include: [/\bshare\b/i, /\bsecrets?\b/i, /\bfriends?\b/i],
    output: "It depends on trust. I would not share too much unless I really trust that person.",
    reasoning: "Immediate grounded privacy-with-friends response",
    confidence: 0.86,
  },
  {
    id: "immediate:free-time-comparison",
    priority: 120,
    category: "casual",
    include: [/\bfree time\b/i, /\b(now|nowadays|today|past|before|difference)\b/i],
    output: "Now people spend more free time online. For me that is mostly games, anime, and internet stuff, while in the past people seemed to go outside or meet friends more.",
    reasoning: "Immediate grounded free-time comparison response",
    confidence: 0.88,
  },
];
